[ci skip] Pushing deployment files for namespace, service accounts and clusterrolebinding
Signed-off-by: jozsefkovacsacc <jozsef.kovacs.acc@gmail.com>

diff --git a/platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml b/platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
--- a/platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
+++ b/platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
@@ -24,11 +18,7 @@ spec:
       app: consortiumchain
       name: {{ .Values.node.name }}
       service.rpc: {{ .Values.node.name }}
-      app.kubernetes.io/name: {{ .Values.node.name }}
-      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-      app.kubernetes.io/managed-by: {{ .Release.Service }}
-      app.kubernetes.io/instance: {{ .Release.Name }} 
-  updateStrategy:
+  strategy:
     type: RollingUpdate
   template:
     metadata:
@@ -37,15 +27,9 @@ spec:
         app: consortiumchain
         name: {{ .Values.node.name }}
         service.rpc: {{ .Values.node.name }}
-        app.kubernetes.io/name: {{ .Values.node.name }}
-        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-        app.kubernetes.io/managed-by: {{ .Release.Service }}
-        app.kubernetes.io/instance: {{ .Release.Name }} 
     spec:
       serviceAccountName: {{ .Values.vault.serviceaccountname }}
       hostname: {{ .Values.node.name }}.{{ .Values.metadata.namespace }}
-      securityContext:
-        fsGroup: 1000
       imagePullSecrets:
           - name: {{ .Values.node.imagePullSecret }}
       volumes:
@@ -67,7 +51,7 @@ spec:
       initContainers:
       - name: certificates-init
         image: {{ .Values.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ .Values.vault.address }}
@@ -85,27 +69,12 @@ spec:
           #!/usr/bin/env sh
           
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
-          echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
           #Login to Vault and to get an approle token
           VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
             -H "Content-Type: application/json" \
@@ -120,19 +89,19 @@ spec:
             --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | \
             jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE" 
-          nodekey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["privateKey"]') 
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" 
+          nodekey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["key"]') 
           echo "${nodekey}" > ${MOUNT_PATH}/nodekey
 
-          vault_secret_key="${VAULT_SECRET_PREFIX}/{{ .Values.vault.tmdir }}" 
+          vault_secret_key="${VAULT_SECRET_PREFIX}/{{ .Values.vault.oriondir }}" 
           LOOKUP_SECRET_RESPONSE=$(curl -sS \
             --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | \
             jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-          orion_key=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["privateKey"]' | base64 -d)  
-          orion_key_pub=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["publicKey"]')    
-          orion_password=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["password"]') 
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
+          orion_key=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["key"]')  
+          orion_key_pub=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["key.pub"]')    
+          orion_password=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["password"]') 
           echo "${orion_key}" > ${MOUNT_PATH}/orion_key.key
           echo "${orion_key_pub}" > ${MOUNT_PATH}/orion_key.pub
           echo "${orion_password}" > ${MOUNT_PATH}/passwordFile 
@@ -144,13 +113,13 @@ spec:
               --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
               ${VAULT_ADDR}/v1/${vault_secret_key} | \
               jq -r 'if .errors then . else . end')
-            validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-            orion_ca=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["rootca_pem"]' | base64 -d)  
-            orion_cer_pem=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ambassadorcrt"]' | base64 -d)    
-            orion_cer_key=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ambassadorkey"]' | base64 -d) 
-            orion_known_server=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["knownServer"]'| base64 -d) 
-            keystore=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')  
-            keystore_password=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["password"]' | base64 -d)
+            validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
+            orion_ca=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["rootca_pem"]' | base64 -d)  
+            orion_cer_pem=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ambassadorcrt"]' | base64 -d)    
+            orion_cer_key=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ambassadorkey"]' | base64 -d) 
+            orion_known_server=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["knownServer"]'| base64 -d) 
+            keystore=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')  
+            keystore_password=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["password"]' | base64 -d)
             echo "${orion_ca}" > ${MOUNT_PATH}/orion_ca.pem
             echo "${orion_cer_pem}" > ${MOUNT_PATH}/orion_cer.pem
             echo "${orion_cer_key}" > ${MOUNT_PATH}/orion_cer.key
@@ -230,10 +199,10 @@ spec:
           - /bin/sh
           - -c
         args:
-          - |            
-            echo -n {{ .Values.staticnodes | toJson | quote }} > {{ .Values.node.mountPath }}/static-nodes.json
-            mkdir -p /tmp/genesis;
-            cat /etc/genesis/genesis.json.base64 | base64 -d > /tmp/genesis/genesis.json
+          - |
+            echo -n {{ .Values.staticnodes | toJson | quote }} > /opt/besu/static-nodes.json
+            mkdir -p $BESU_GENESIS_DIR;
+            cat {{ .Values.node.mountPath }}/genesis/genesis.json.base64 | base64 -d > $BESU_GENESIS_DIR/genesis.json
             tr -d "\n\r" < /secrets/orion_key.pub > /secrets/nodekey.pub
             args="--rpc-http-enabled --rpc-http-api=ETH,NET,IBFT,DEBUG,ADMIN,WEB3,EEA,PRIV --rpc-ws-enabled --rpc-ws-api=ETH,NET,WEB3 --p2p-port {{ .Values.node.ports.p2p }} --rpc-http-port {{ .Values.node.ports.rpc }} --rpc-ws-port={{ .Values.node.ports.ws }}"
             if  {{ $.Values.orion.tls }} == "true" 
@@ -242,15 +211,13 @@ spec:
             else
               tls_args="--privacy-url=http://{{ .Values.node.name }}.{{ .Values.metadata.namespace }}:{{ .Values.orion.ports.clientport }}"
             fi
-            
             exec /opt/besu/bin/besu \
             --identity={{ .Values.node.name }} \
             --discovery-enabled=false \
             --node-private-key-file=/secrets/nodekey \
-            --data-path={{ .Values.node.mountPath }} \
-            --genesis-file=/tmp/genesis/genesis.json \
+            --genesis-file=/etc/genesis/genesis.json \
             --logging=DEBUG \
-            --nat-method=AUTO \
+            --nat-method=MANUAL \
             --tx-pool-retention-hours=999 \
             --tx-pool-max-size=1024 \
             --p2p-enabled=true \
@@ -263,10 +230,8 @@ spec:
             --min-gas-price=0 \
             --privacy-enabled=true \
             --privacy-public-key-file=/secrets/nodekey.pub \
-            --Xdns-enabled=true \
-            --Xdns-update-enabled=true \
             $args \
-            $tls_args            
+            $tls_args \
         ports:
           - name: json-rpc
             containerPort: {{ .Values.node.ports.rpc}}
@@ -278,6 +243,8 @@ spec:
             containerPort: {{ .Values.node.ports.p2p }}
             protocol: TCP
         env:
+          - name: BESU_GENESIS_DIR
+            value: {{ .Values.node.mountPath }}
           - name: POD_IP
             valueFrom:
               fieldRef:
@@ -288,7 +255,7 @@ spec:
                 fieldPath: metadata.name
         volumeMounts:
         - name: {{ .Values.node.name }}-genesis-volume
-          mountPath: /etc/genesis
+          mountPath: {{ .Values.node.mountPath }}/genesis
         - name: certificates
           mountPath: /secrets
         - name: {{ .Values.node.name }}-pv
diff --git a/platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml b/platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml
--- a/platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml
+++ b/platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
@@ -24,11 +18,7 @@ spec:
       app: consortiumchain
       name: {{ .Values.node.name }}
       service.rpc: {{ .Values.node.name }}
-      app.kubernetes.io/name: {{ .Values.node.name }}
-      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-      app.kubernetes.io/managed-by: {{ .Release.Service }}
-      app.kubernetes.io/instance: {{ .Release.Name }} 
-  updateStrategy:
+  strategy:
     type: RollingUpdate
   template:
     metadata:
@@ -37,15 +27,9 @@ spec:
         app: consortiumchain
         name: {{ .Values.node.name }}
         service.rpc: {{ .Values.node.name }}
-        app.kubernetes.io/name: {{ .Values.node.name }}
-        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-        app.kubernetes.io/managed-by: {{ .Release.Service }}
-        app.kubernetes.io/instance: {{ .Release.Name }} 
     spec:
       serviceAccountName: {{ .Values.vault.serviceaccountname }}
       hostname: {{ .Values.node.name }}.{{ .Values.metadata.namespace }}
-      securityContext:
-        fsGroup: 1000
       imagePullSecrets:
           - name: {{ .Values.node.imagePullSecret }}
       volumes:
@@ -61,7 +45,7 @@ spec:
       initContainers:
       - name: certificates-init
         image: {{ .Values.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ .Values.vault.address }}
@@ -77,26 +61,12 @@ spec:
         args:
         - |-
           #!/usr/bin/env sh
-
+          
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
           echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
@@ -114,8 +84,8 @@ spec:
             --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | \
             jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE" 
-          nodekey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["key"]') 
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" 
+          nodekey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["key"]') 
           echo "${nodekey}" > ${MOUNT_PATH}/nodekey
 
           if [ {{ $.Values.node.tls }} == "true" ]
@@ -125,9 +95,9 @@ spec:
               --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
               ${VAULT_ADDR}/v1/${vault_secret_key} | \
               jq -r 'if .errors then . else . end')
-            validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-            keystore=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')  
-            keystore_password=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["password"]' | base64 -d)
+            validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
+            keystore=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')  
+            keystore_password=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["password"]' | base64 -d)
             echo "${keystore}" > ${MOUNT_PATH}/keystore
             base64 -d ${MOUNT_PATH}/keystore > ${MOUNT_PATH}/keystore.pkcs12
             echo "${keystore_password}" > ${MOUNT_PATH}/keystore_password
@@ -167,38 +137,33 @@ spec:
           - /bin/sh
           - -c
         args:
-          - | 
-            echo -n {{ .Values.staticnodes | toJson | quote }} > {{ .Values.node.mountPath }}/static-nodes.json
-            mkdir -p /tmp/genesis;
-            cat /etc/genesis/genesis.json.base64 | base64 -d > /tmp/genesis/genesis.json
+          - |
+            echo -n {{ .Values.staticnodes | toJson | quote }} > /opt/besu/static-nodes.json
+            mkdir -p $BESU_GENESIS_DIR;
+            cat {{ .Values.node.mountPath }}/genesis/genesis.json.base64 | base64 -d > $BESU_GENESIS_DIR/genesis.json
             args="--rpc-http-enabled --rpc-http-api=ETH,NET,IBFT,DEBUG,ADMIN,WEB3 --rpc-ws-enabled --rpc-ws-api=ETH,NET,WEB3 --p2p-port {{ .Values.node.ports.p2p }} --rpc-http-port {{ .Values.node.ports.rpc }} --rpc-ws-port={{ .Values.node.ports.ws }}"
             if  {{ $.Values.node.tls }} == "true" 
             then
               tls_args="--privacy-tls-enabled --privacy-tls-keystore-file=/secrets/keystore.pkcs12 --privacy-tls-keystore-password-file=/secrets/keystore_password"
             fi
-            
             exec /opt/besu/bin/besu \
             --identity={{ .Values.node.name }} \
             --discovery-enabled=false \
             --node-private-key-file=/secrets/nodekey \
-            --data-path={{ .Values.node.mountPath }} \
-            --genesis-file=/tmp/genesis/genesis.json \
+            --genesis-file=/etc/genesis/genesis.json \
             --logging=DEBUG \
-            --nat-method=AUTO \
+            --nat-method=MANUAL \
             --tx-pool-retention-hours=999 \
             --tx-pool-max-size=1024 \
             --p2p-enabled=true \
             --p2p-host=0.0.0.0 \
             --max-peers=25 \
             --host-whitelist="*" \
-            --min-gas-price=0 \
             --rpc-http-host=0.0.0.0 \
             --rpc-http-cors-origins="all" \
             --rpc-ws-host=0.0.0.0 \
-            --Xdns-enabled=true \
-            --Xdns-update-enabled=true \
             $args \
-            $tls_args            
+            $tls_args \
         ports:
           - name: json-rpc
             containerPort: {{ .Values.node.ports.rpc}}
@@ -210,6 +175,8 @@ spec:
             containerPort: {{ .Values.node.ports.p2p }}
             protocol: TCP
         env:
+          - name: BESU_GENESIS_DIR
+            value: {{ .Values.node.mountPath }}
           - name: POD_IP
             valueFrom:
               fieldRef:
@@ -220,12 +187,11 @@ spec:
                 fieldPath: metadata.name
         volumeMounts:
         - name: {{ .Values.node.name }}-genesis-volume
-          mountPath: /etc/genesis
+          mountPath: {{ .Values.node.mountPath }}/genesis
         - name: certificates
           mountPath: /secrets
-          readOnly: true
         - name: {{ .Values.node.name }}-pv
-          mountPath: {{ .Values.node.mountPath }}          
+          mountPath: {{ .Values.node.mountPath }}
       restartPolicy: Always
   volumeClaimTemplates: 
     - metadata:
diff --git a/platforms/hyperledger-fabric/charts/create_channel/templates/create_channel.yaml b/platforms/hyperledger-fabric/charts/create_channel/templates/create_channel.yaml
--- a/platforms/hyperledger-fabric/charts/create_channel/templates/create_channel.yaml
+++ b/platforms/hyperledger-fabric/charts/create_channel/templates/create_channel.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -28,7 +22,6 @@ spec:
         app: createchannel-{{ $.Values.channel.name }}
         app.kubernetes.io/name: createchannel-{{ $.Values.channel.name }}
         app.kubernetes.io/instance: {{ .Release.Name }} 
-        app.kubernetes.io/managed-by: {{ .Release.Service }}
     spec:
       restartPolicy: "OnFailure"
       serviceAccountName: {{ $.Values.vault.serviceaccountname }}
@@ -52,7 +45,7 @@ spec:
       initContainers:
       - name: certificates-init
         image: {{ $.Values.metadata.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ $.Values.vault.address }}
@@ -71,24 +64,10 @@ spec:
         - |-
           #!/usr/bin/env sh
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
 
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
@@ -106,9 +85,9 @@ spec:
           OUTPUT_PATH="${MOUNT_PATH}/orderer/tls"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
 
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" 
 
-          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ca.crt"]')
+          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ca.crt"]')
 
           mkdir -p ${OUTPUT_PATH}
           echo "${TLS_CA_CERT}" >> ${OUTPUT_PATH}/ca.crt
@@ -118,25 +97,22 @@ spec:
 
           OUTPUT_PATH="${MOUNT_PATH}/admin/msp"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" 
 
-          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["admincerts"]')
-          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["cacerts"]')
-          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')
-          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["signcerts"]')
-          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlscacerts"]')
+          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["admincerts"]')
+          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["cacerts"]')
+          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')
+          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["signcerts"]')
 
           mkdir -p ${OUTPUT_PATH}/admincerts
           mkdir -p ${OUTPUT_PATH}/cacerts
           mkdir -p ${OUTPUT_PATH}/keystore
           mkdir -p ${OUTPUT_PATH}/signcerts
-          mkdir -p ${OUTPUT_PATH}/tlscacerts
 
           echo "${ADMINCERT}" >> ${OUTPUT_PATH}/admincerts/admin.crt
           echo "${CACERTS}" >> ${OUTPUT_PATH}/cacerts/ca.crt
           echo "${KEYSTORE}" >> ${OUTPUT_PATH}/keystore/server.key
           echo "${SIGNCERTS}" >> ${OUTPUT_PATH}/signcerts/server.crt
-          echo "${TLSCACERTS}" >> ${OUTPUT_PATH}/tlscacerts/tlsca.crt
         volumeMounts:
         {{ if .Values.vault.tls  }}
         - name: vaultca
@@ -148,7 +124,7 @@ spec:
       containers:
       - name: createchannel
         image: {{ $.Values.metadata.images.fabrictools }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         stdin: true
         tty: true
         command: ["sh", "-c"]
@@ -170,22 +146,11 @@ spec:
             echo "Channel ${CHANNEL_NAME} is already created."
           else
             echo "Creating Channel ${CHANNEL_NAME}"
-            version1_4=`echo $NETWORK_VERSION | grep -c 1.4`
             if [ "$tls_status" = "true" ]
             then
-              if [ $version1_4 = 1 ]
-              then
-                peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f channel.tx --tls ${CORE_PEER_TLS_ENABLED} --cafile ${ORDERER_CA}
-              else
-                peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f channel.tx --tls ${CORE_PEER_TLS_ENABLED} --cafile ${ORDERER_CA} --outputBlock /tmp/${CHANNEL_NAME}.block
-              fi
+              peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f channel.tx --tls ${CORE_PEER_TLS_ENABLED} --cafile ${ORDERER_CA}
             else
-              if [ $version1_4 = 1 ]
-              then 
-                peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f channel.tx
-              else
-                peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f channel.tx --outputBlock /tmp/${CHANNEL_NAME}.block
-              fi
+              peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f channel.tx 
             fi
           fi
         workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
diff --git a/platforms/hyperledger-fabric/charts/fabric_cli/templates/deployment.yaml b/platforms/hyperledger-fabric/charts/fabric_cli/templates/deployment.yaml
--- a/platforms/hyperledger-fabric/charts/fabric_cli/templates/deployment.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric_cli/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -40,7 +34,7 @@ spec:
       initContainers:
       - name: certificates-init
         image: {{ $.Values.metadata.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ $.Values.vault.address }}
@@ -59,24 +53,10 @@ spec:
         - |-
           #!/usr/bin/env sh
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
 
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
@@ -94,9 +74,9 @@ spec:
           OUTPUT_PATH="${MOUNT_PATH}/orderer/tls"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
 
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ca.crt"]')
+          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ca.crt"]')
 
           mkdir -p ${OUTPUT_PATH}
           echo "${TLS_CA_CERT}" >> ${OUTPUT_PATH}/ca.crt
@@ -106,13 +86,13 @@ spec:
 
           OUTPUT_PATH="${MOUNT_PATH}/admin/msp"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["admincerts"]')
-          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["cacerts"]')
-          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')
-          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["signcerts"]')
-          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlscacerts"]')
+          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["admincerts"]')
+          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["cacerts"]')
+          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')
+          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["signcerts"]')
+          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
 
           mkdir -p ${OUTPUT_PATH}/admincerts
           mkdir -p ${OUTPUT_PATH}/cacerts
@@ -136,7 +116,7 @@ spec:
       containers:
       - name: cli
         image: {{ $.Values.metadata.images.fabrictools }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         stdin: true
         tty: true
         command: ["sh", "-c", "/bin/bash"]
@@ -155,7 +135,7 @@ spec:
         - name: CORE_PEER_TLS_ENABLED
           value: "{{ .Values.peer.tlsstatus }}"
         - name: CORE_PEER_TLS_ROOTCERT_FILE
-          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/tlscacerts/tlsca.crt
+          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/cacerts/ca.crt
         - name: ORDERER_CA
           value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt
         - name: ORDERER_URL
diff --git a/platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml b/platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -22,10 +16,6 @@ spec:
     metadata:
       labels:
         app: installchaincode-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
-        app.kubernetes.io/name: installchaincode-{{ $.Values.chaincode.name }}{{ $.Values.chaincode.version }}
-        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-        app.kubernetes.io/managed-by: {{ .Release.Service }}
-        app.kubernetes.io/instance: {{ .Release.Name }}
     spec:
       restartPolicy: OnFailure
       serviceAccountName: {{ $.Values.vault.serviceaccountname }}
@@ -46,7 +36,7 @@ spec:
       initContainers:
       - name: certificates-init
         image: {{ $.Values.metadata.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ $.Values.vault.address }}
@@ -60,38 +50,15 @@ spec:
           value: "{{ $.Values.vault.orderersecretprefix }}"
         - name: MOUNT_PATH
           value: /secret
-        - name: NETWORK_VERSION
-          value: "{{ $.Values.metadata.network.version }}"
-        - name: GIT_PATH
-          value: "{{ $.Values.vault.secretgitprivatekey }}"
-        - name: GIT_PASSWORD  
-          valueFrom:
-            secretKeyRef:
-              name: gitpassword
-              key: password
         command: ["sh", "-c"]
         args:
         - |-
           #!/usr/bin/env sh
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
 
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
@@ -111,9 +78,9 @@ spec:
             --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
 
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ca.crt"]')
+          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ca.crt"]')
 
           mkdir -p ${OUTPUT_PATH}
           echo "${TLS_CA_CERT}" >> ${OUTPUT_PATH}/ca.crt
@@ -123,13 +90,13 @@ spec:
 
           OUTPUT_PATH="${MOUNT_PATH}/admin/msp"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["admincerts"]')
-          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["cacerts"]')
-          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')
-          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["signcerts"]')
-          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlscacerts"]')
+          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["admincerts"]')
+          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["cacerts"]')
+          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')
+          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["signcerts"]')
+          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
 
           mkdir -p ${OUTPUT_PATH}/admincerts
           mkdir -p ${OUTPUT_PATH}/cacerts
@@ -144,21 +111,15 @@ spec:
           echo "${TLSCACERTS}" >> ${OUTPUT_PATH}/tlscacerts/tlsca.crt
 
           # GIT user creds
-          # This task write the git credentials to Vault
-          curl \
-            -H "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-            -H "Content-Type: application/json" \
-            -X POST \
-            -d '{ "data": {"git_password":"'"$GIT_PASSWORD"'"}}' \
-            ${VAULT_ADDR}/v1/${GIT_PATH}
-          
-          # Check git credentials
-          LOOKUP_SECRET_RESPONSE=$(curl -sS  \
-            --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-            ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${GIT_PATH})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-
-          echo "${GIT_PASSWORD}" >> ${MOUNT_PATH}/user_cred
+          GIT_SSH_PRIVATE_KEY={{ $.Values.vault.secretgitprivatekey }}
+          vault_secret_key=$(echo ${GIT_SSH_PRIVATE_KEY} |awk -F "?" '{print $1}')
+          vault_data_key=$(echo ${GIT_SSH_PRIVATE_KEY} |awk -F "?" '{print $2}')
+          LOOKUP_SECRET_RESPONSE=$(curl -sS \
+              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+          ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
+          VALUE_OF_SECRET=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r ".data[\"${vault_data_key}\"]")         
+          echo "${VALUE_OF_SECRET}" >> ${MOUNT_PATH}/user_cred
 
         volumeMounts:
         {{ if .Values.vault.tls  }}
@@ -171,133 +132,29 @@ spec:
       containers:
       - name: installchaincode
         image: {{ $.Values.metadata.images.fabrictools }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         stdin: true
         tty: true
         command: ["sh", "-c"]
         args:
         - |-
-          #!/bin/bash sh
           ## Git repository clone for chaincode
           mkdir -p /root/.ssh/          
           apk add curl openssh
           ssh-keyscan {{ $.Values.chaincode.repository.hostname }} > /root/.ssh/known_hosts
           git_password=$(cat /opt/gopath/src/github.com/hyperledger/fabric/crypto/user_cred)
-          cd /tmp && git clone https://{{ $.Values.chaincode.repository.git_username }}:$GIT_PASSWORD@{{ $.Values.chaincode.repository.url }} -b {{ $.Values.chaincode.repository.branch }} chaincode
-          ls
-          echo $GOPATH
-          if [ ${CC_RUNTIME_LANGUAGE} = "golang" ]
-          then
-            ## Copying desired chaincode to a location relative to $GOPATH/src
-            mkdir -p $GOPATH/src/github.com/chaincode
-            cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
+          cd /tmp && git clone https://{{ $.Values.chaincode.repository.git_username }}:$git_password@{{ $.Values.chaincode.repository.url }} -b {{ $.Values.chaincode.repository.branch }} chaincode
 
-            # Get dependencies
-            mkdir -p $GOPATH/bin && curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
-            cd $GOPATH/src/github.com/chaincode && dep ensure
+          ## Copying desired chaincode to a location relative to $GOPATH/src
+          mkdir -p $GOPATH/src/github.com/chaincode
+          cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
 
-            #chaincode path
-            CC_SRC_PATH="github.com/chaincode/${CHAINCODE_NAME}/${CHAINCODE_MAINDIR}"
-
-            if ! [ -d "vendor" ];then
-              GO111MODULE=on go mod vendor
-              CC_SRC_PATH="${PWD}"
-            fi
-
-          elif [ ${CC_RUNTIME_LANGUAGE} = "java" ]
-          then
-            ## Copying desired chaincode to a location 
-            mkdir -p $GOPATH/src/github.com/chaincode
-            cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
-
-            # Get dependencies
-            apk add openjdk8
-            java -version
-            apk add gradle
-            gradle -v
-            cd $GOPATH/src/github.com/chaincode && dep ensure
-
-            CC_SRC_PATH="/$GOPATH/src/github.com/chaincode/"
-
-            echo "CC_SRC_PATH= $CC_SRC_PATH"
-            current_path=`pwd`
-            echo $current_path
-
-            echo "Compiling Java code..."
-            chmod +x gradlew
-            ./gradlew installDist --stacktrace
-            cd $current_path
-            echo "Finished compiling Java code"
-
-            #chaincode path
-            CC_SRC_PATH=$CC_SRC_PATH/build/install/${CHAINCODE_NAME}
-
-            echo $CC_SRC_PATH
-          elif [ ${CC_RUNTIME_LANGUAGE} = "node" ]
-          then
-            ## Copying desired chaincode to a location relative to $GOPATH/src
-            mkdir -p $GOPATH/src/github.com/chaincode
-            cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
-
-            #chaincode path
-            CC_SRC_PATH="${GOPATH}/src/github.com/chaincode/${CHAINCODE_NAME}/${CHAINCODE_MAINDIR}"
-          fi
-          version1_4=`echo $NETWORK_VERSION | grep -c 1.4`
-          if [ $version1_4 = 1 ];then
-
-            ## Checking installed chaincode
-            INSTALLED=$(peer chaincode list --installed | grep "Name: ${CHAINCODE_NAME}, Version: ${CHAINCODE_VERSION},")
-            if [ -n "${INSTALLED}" ]
-            then
-              echo "chaincode ${CHAINCODE_NAME} version ${CHAINCODE_VERSION} is installed, skipping... "
-              exit 0
-            fi
-
-            echo "Installing Chaincode for ${NETWORK_VERSION}"
-            ## Installing chaincode on a peer
-            peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p ${CC_SRC_PATH} --lang ${CC_RUNTIME_LANGUAGE}
-            echo "Chaincode installed for Fabric v.1.4.X"         
-          else
-
-            ## Checking installed chaincode
-            INSTALLED=$(peer lifecycle chaincode queryinstalled -O json | jq '.installed_chaincodes?' | \
-              jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
-            if [ -n "${INSTALLED}" ]
-            then
-              echo "chaincode ${CHAINCODE_NAME}_${CHAINCODE_VERSION} is installed, skipping... "
-              exit 0
-            fi
-
-            echo "Installing Chaincode for ${NETWORK_VERSION}"
-            if [ $PEER_NAME = "peer0" ];then
-              ## packaging chaincode
-              echo "Packaging chaincode for the first peer"
-              peer lifecycle chaincode package ${CHAINCODE_NAME}.tar.gz --path ${CC_SRC_PATH} --lang ${CC_RUNTIME_LANGUAGE} --label ${CHAINCODE_NAME}_${CHAINCODE_VERSION}
-            else
-              export CORE_PEER_ADDRESS=${PEER0_ADDRESS}
-              echo "Extracting package id"
-              peer lifecycle chaincode queryinstalled > log.txt
-              PACKAGE_ID=$(cat log.txt | grep "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" | sed -n "/${CC_NAME}_${CC_VERSION}/{s/^Package ID: //; s/, Label:.*$//; p;}")
-              echo "Package Id Extracted ${PACKAGE_ID}"
-              peer lifecycle chaincode getinstalledpackage --package-id ${PACKAGE_ID}
-              export CORE_PEER_ADDRESS=${PEER_ADDRESS}
-              export CHAINCODE_NAME=${PACKAGE_ID}
-              echo "installing ${CHAINCODE_NAME} on ${CORE_PEER_ADDRESS}"
-            fi
-            ## Installing Chaincode
-            peer lifecycle chaincode install ${CHAINCODE_NAME}.tar.gz
-            echo "Chaincode installed for Fabric v.2.X"
-            #query installed
-            echo "peer query installed"
-            peer lifecycle chaincode queryinstalled
-          fi
+          # Get dependencies
+          mkdir -p $GOPATH/bin && curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
+          cd $GOPATH/src/github.com/chaincode && dep ensure
+          ## Installing chaincode on a peer
+          peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p github.com/chaincode/${CHAINCODE_NAME}/${CHAINCODE_MAINDIR}
         env:
-        - name: PEER_NAME
-          value: {{ $.Values.peer.name }}
-        - name: PEER0_ADDRESS
-          value: peer0.{{ $.Values.metadata.namespace }}:7051
-        - name: PEER_ADDRESS
-          value: {{ $.Values.peer.address }}
         - name: CORE_VM_ENDPOINT
           value: unix:///host/var/run/docker.sock
         - name: FABRIC_LOGGING_SPEC
@@ -311,7 +168,7 @@ spec:
         - name: CORE_PEER_TLS_ENABLED
           value: "{{ $.Values.peer.tlsstatus }}"
         - name: CORE_PEER_TLS_ROOTCERT_FILE
-          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/tlscacerts/tlsca.crt
+          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/cacerts/ca.crt
         - name: ORDERER_CA
           value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt
         - name: ORDERER_URL
@@ -326,10 +183,6 @@ spec:
           value: "{{ $.Values.chaincode.version }}"
         - name: CORE_CHAINCODE_BUILDER
           value: "{{ $.Values.chaincode.builder }}"
-        - name: NETWORK_VERSION
-          value: "{{ $.Values.metadata.network.version }}"
-        - name: CC_RUNTIME_LANGUAGE
-          value: "{{ $.Values.chaincode.lang }}"
         volumeMounts:
         - name: certificates
           mountPath: /opt/gopath/src/github.com/hyperledger/fabric/crypto
diff --git a/platforms/hyperledger-fabric/charts/instantiate_chaincode/templates/instantiate_chaincode.yaml b/platforms/hyperledger-fabric/charts/instantiate_chaincode/templates/instantiate_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/instantiate_chaincode/templates/instantiate_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/instantiate_chaincode/templates/instantiate_chaincode.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -22,10 +16,6 @@ spec:
     metadata:
       labels:
         app: instantiatechaincode-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
-        app.kubernetes.io/name: instantiatechaincode-{{ $.Values.chaincode.name }}
-        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-        app.kubernetes.io/managed-by: {{ .Release.Service }}
-        app.kubernetes.io/instance: {{ .Release.Name }}
     spec:
       restartPolicy: OnFailure
       serviceAccountName: {{ $.Values.vault.serviceaccountname }}
@@ -46,7 +36,7 @@ spec:
       initContainers:
       - name: certificates-init
         image: {{ $.Values.metadata.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ $.Values.vault.address }}
@@ -65,26 +55,11 @@ spec:
         - |-
           #!/usr/bin/env sh
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
-          
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
           echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
           # Login to Vault and so I can get an approle token
@@ -102,9 +77,9 @@ spec:
             --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
 
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ca.crt"]')
+          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ca.crt"]')
 
           mkdir -p ${OUTPUT_PATH}
           echo "${TLS_CA_CERT}" >> ${OUTPUT_PATH}/ca.crt
@@ -116,25 +91,22 @@ spec:
           LOOKUP_SECRET_RESPONSE=$(curl -sS  \
             --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["admincerts"]')
-          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["cacerts"]')
-          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')
-          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["signcerts"]')
-          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlscacerts"]')
+          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["admincerts"]')
+          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["cacerts"]')
+          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')
+          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["signcerts"]')
 
           mkdir -p ${OUTPUT_PATH}/admincerts
           mkdir -p ${OUTPUT_PATH}/cacerts
           mkdir -p ${OUTPUT_PATH}/keystore
           mkdir -p ${OUTPUT_PATH}/signcerts
-          mkdir -p ${OUTPUT_PATH}/tlscacerts
 
           echo "${ADMINCERT}" >> ${OUTPUT_PATH}/admincerts/admin.crt
           echo "${CACERTS}" >> ${OUTPUT_PATH}/cacerts/ca.crt
           echo "${KEYSTORE}" >> ${OUTPUT_PATH}/keystore/server.key
           echo "${SIGNCERTS}" >> ${OUTPUT_PATH}/signcerts/server.crt
-          echo "${TLSCACERTS}" >> ${OUTPUT_PATH}/tlscacerts/tlsca.crt
         volumeMounts:
         {{ if .Values.vault.tls  }}
         - name: vaultca
@@ -146,7 +118,7 @@ spec:
       containers:
       - name: instantiatechaincode
         image: {{ $.Values.metadata.images.fabrictools }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         stdin: true
         tty: true
         command: ["sh", "-c"]
@@ -155,9 +127,9 @@ spec:
           echo $INSTANTIATION_ARGUMENTS>INSTANTIATION_ARGUMENTS.txt
           INSTANTIATION_ARGUMENTS=$(< INSTANTIATION_ARGUMENTS.txt)
           {{ if $.Values.chaincode.endorsementpolicies  }}
-            peer chaincode instantiate -o ${ORDERER_URL} --tls ${CORE_PEER_TLS_ENABLED} --cafile ${ORDERER_CA} -C ${CHANNEL_NAME} -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -c '{"Args":['${INSTANTIATION_ARGUMENTS}']}' -P {{ $.Values.chaincode.endorsementpolicies | quote}} --lang ${CC_RUNTIME_LANGUAGE}
+            peer chaincode instantiate -o ${ORDERER_URL} --tls ${CORE_PEER_TLS_ENABLED} --cafile ${ORDERER_CA} -C ${CHANNEL_NAME} -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -c '{"Args":['${INSTANTIATION_ARGUMENTS}']}' -P {{ $.Values.chaincode.endorsementpolicies | quote}}
           {{ else }}
-            peer chaincode instantiate -o ${ORDERER_URL} --tls ${CORE_PEER_TLS_ENABLED} --cafile ${ORDERER_CA} -C ${CHANNEL_NAME} -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -c '{"Args":['${INSTANTIATION_ARGUMENTS}']}' --lang ${CC_RUNTIME_LANGUAGE}
+            peer chaincode instantiate -o ${ORDERER_URL} --tls ${CORE_PEER_TLS_ENABLED} --cafile ${ORDERER_CA} -C ${CHANNEL_NAME} -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -c '{"Args":['${INSTANTIATION_ARGUMENTS}']}'
           {{ end }}
         env:
         - name: CORE_VM_ENDPOINT
@@ -173,7 +145,7 @@ spec:
         - name: CORE_PEER_TLS_ENABLED
           value: "{{ $.Values.peer.tlsstatus }}"
         - name: CORE_PEER_TLS_ROOTCERT_FILE
-          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/tlscacerts/tlsca.crt
+          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/cacerts/ca.crt
         - name: ORDERER_CA
           value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt
         - name: ORDERER_URL
@@ -190,8 +162,6 @@ spec:
           value: "{{ $.Values.channel.name }}"
         - name: INSTANTIATION_ARGUMENTS
           value: '{{ $.Values.chaincode.instantiationargs }}'
-        - name: CC_RUNTIME_LANGUAGE
-          value: "{{ $.Values.chaincode.lang }}"
         volumeMounts:
         - name: certificates
           mountPath: /opt/gopath/src/github.com/hyperledger/fabric/crypto
diff --git a/platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml b/platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml
--- a/platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml
+++ b/platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
@@ -15,14 +9,6 @@ metadata:
     app.kubernetes.io/managed-by: {{ .Release.Service }}
     app.kubernetes.io/instance: {{ .Release.Name }}
     {{- include "labels.custom" . | nindent 2 }}
-  annotations:
-    {{- if $.Values.annotations }}
-    {{- range $key, $value := $.Values.annotations.deployment }}
-    {{- range $k, $v := $value }}
-      {{ $k }}: {{ $v | quote }}
-    {{- end }}
-    {{- end }}
-    {{- end }}     
 spec:
   updateStrategy:
     type: RollingUpdate
@@ -31,7 +17,6 @@ spec:
   selector:
     matchLabels:
       app: {{ $.Values.orderer.name }}
-      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
       app.kubernetes.io/name: {{ $.Values.orderer.name }}
       app.kubernetes.io/instance: {{ .Release.Name }}
   template:
@@ -40,7 +25,6 @@ spec:
         checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
       labels:
         app: {{ $.Values.orderer.name }}
-        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
         app.kubernetes.io/name: {{ $.Values.orderer.name }}
         app.kubernetes.io/instance: {{ .Release.Name }} 
     spec:    
@@ -68,7 +52,7 @@ spec:
       initContainers:
       - name: kafka-healthcheck
         image: {{ $.Values.metadata.images.healthcheck }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         command: ["sh", "-c"]
         args:
         - |-
@@ -120,7 +104,7 @@ spec:
           fi
       - name: certificates-init
         image: {{ $.Values.metadata.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ $.Values.vault.address }}
@@ -137,24 +121,10 @@ spec:
         - |-
           #!/usr/bin/env sh
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
 
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
@@ -173,11 +143,11 @@ spec:
 
           OUTPUT_PATH="${MOUNT_PATH}/tls"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ca.crt"]')
-          TLS_SERVER_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["server.crt"]')
-          TLS_SERVER_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["server.key"]')
+          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ca.crt"]')
+          TLS_SERVER_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["server.crt"]')
+          TLS_SERVER_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["server.key"]')
 
           mkdir -p ${OUTPUT_PATH}
           echo "${TLS_CA_CERT}" >> ${OUTPUT_PATH}/ca.crt
@@ -189,13 +159,13 @@ spec:
 
           OUTPUT_PATH="${MOUNT_PATH}/msp"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["admincerts"]')
-          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["cacerts"]')
-          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')
-          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["signcerts"]')
-          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlscacerts"]')
+          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["admincerts"]')
+          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["cacerts"]')
+          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')
+          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["signcerts"]')
+          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
 
           mkdir -p ${OUTPUT_PATH}/admincerts
           mkdir -p ${OUTPUT_PATH}/cacerts
@@ -223,8 +193,6 @@ spec:
         command: ["sh", "-c", "cat /var/hyperledger/orderer/genesis/genesis.block.base64 | base64 -d > /var/hyperledger/orderer/orderer.genesis.block && orderer"]
         ports:
         - containerPort: 7050
-        - name: operations
-          containerPort: 9443
         envFrom:
         - configMapRef:
             name: {{ $.Values.orderer.name }}-config
@@ -237,44 +205,6 @@ spec:
         - name: certificates
           mountPath: /var/hyperledger/orderer/crypto
           readOnly: true
-        resources:
-          requests:
-            memory: {{ .Values.config.pod.resources.requests.memory }}
-            cpu: {{ .Values.config.pod.resources.requests.cpu }}
-          limits:
-            memory: {{ .Values.config.pod.resources.limits.memory }}
-            cpu: {{ .Values.config.pod.resources.limits.cpu }}
-      - name: grpc-web
-        image: "ghcr.io/hyperledger-labs/grpc-web:latest"        
-        ports:
-        - name: grpc-web
-          containerPort: 7443        
-        env:
-        - name: BACKEND_ADDRESS
-          value: "{{ $.Values.orderer.name }}.{{ $.Values.metadata.namespace }}:{{ $.Values.service.ports.grpc.clusteripport }}"
-        - name: SERVER_TLS_CERT_FILE
-          value: "/certs/tls/server.crt"
-        - name: SERVER_TLS_KEY_FILE
-          value: "/certs/tls/server.key"
-        - name: BACKEND_TLS_CA_FILES
-          value: "/certs/tls/ca.crt"
-        - name: SERVER_BIND_ADDRESS
-          value: "0.0.0.0"
-        - name: SERVER_HTTP_DEBUG_PORT
-          value: "8080"
-        - name: SERVER_HTTP_TLS_PORT
-          value: "7443"
-        - name: BACKEND_TLS
-          value: "true"
-        - name: SERVER_HTTP_MAX_WRITE_TIMEOUT
-          value: 5m
-        - name: SERVER_HTTP_MAX_READ_TIMEOUT
-          value: 5m
-        - name: USE_WEBSOCKETS
-          value: "true"
-        volumeMounts:        
-        - name: certificates
-          mountPath: /certs
   volumeClaimTemplates:
   #Lables are not being taken by Kubernetes as it dynamically creates PVC
   - metadata:
diff --git a/platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml b/platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml
--- a/platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml
+++ b/platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
@@ -16,14 +10,6 @@ metadata:
     app.kubernetes.io/managed-by: {{ .Release.Service }}
     app.kubernetes.io/instance: {{ .Release.Name }}
     {{- include "labels.custom" . | nindent 2 }}
-  annotations:
-    {{- if $.Values.annotations }}
-    {{- range $key, $value := $.Values.annotations.deployment }}
-    {{- range $k, $v := $value }}
-      {{ $k }}: {{ $v | quote }}
-    {{- end }}
-    {{- end }}
-    {{- end }}     
 spec:
   updateStrategy:
     type: RollingUpdate 
@@ -33,7 +19,6 @@ spec:
     matchLabels:
       app: {{ $.Values.peer.name }}
       app.kubernetes.io/name: {{ $.Values.peer.name }}
-      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
       app.kubernetes.io/instance: {{ .Release.Name }}
   template:
     metadata:
@@ -42,16 +27,36 @@ spec:
       labels:
         app: {{ $.Values.peer.name }}
         app.kubernetes.io/name: {{ $.Values.peer.name }}
-        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
         app.kubernetes.io/instance: {{ .Release.Name }}
     spec:   
       serviceAccountName: {{ $.Values.vault.serviceaccountname }}
       imagePullSecrets:
         - name: {{ $.Values.vault.imagesecretname }}
+      volumes:
+      {{ if .Values.vault.tls  }}
+      - name: vaultca
+        secret:
+          secretName: {{ $.Values.vault.tls }}
+          items:
+          - key: ca.crt.pem
+            path: ca-certificates.crt
+      {{ end }}
+      - name: certificates
+        emptyDir:
+          medium: Memory
+      - name: dockersocket
+        hostPath:
+          path: /var/run/docker.sock
+      - name: {{ $.Values.peer.name }}-msp-config-volume
+        configMap:
+          name: {{ $.Values.peer.name }}-msp-config
+          items:
+            - key: mspconfig
+              path: mspconfig
       initContainers:
       - name: certificates-init
         image: {{ $.Values.metadata.images.alpineutils}}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ $.Values.vault.address }}
@@ -68,24 +73,10 @@ spec:
         - |-
           #!/usr/bin/env sh
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
 
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
@@ -103,11 +94,11 @@ spec:
           OUTPUT_PATH="${MOUNT_PATH}/tls"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
 
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ca.crt"]')
-          TLS_SERVER_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["server.crt"]')
-          TLS_SERVER_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["server.key"]')
+          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ca.crt"]')
+          TLS_SERVER_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["server.crt"]')
+          TLS_SERVER_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["server.key"]')
 
           mkdir -p ${OUTPUT_PATH}
           echo "${TLS_CA_CERT}" >> ${OUTPUT_PATH}/ca.crt
@@ -119,13 +110,13 @@ spec:
 
           OUTPUT_PATH="${MOUNT_PATH}/msp"
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["admincerts"]')
-          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["cacerts"]')
-          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')
-          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["signcerts"]')
-          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlscacerts"]')
+          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["admincerts"]')
+          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["cacerts"]')
+          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')
+          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["signcerts"]')
+          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
 
           mkdir -p ${OUTPUT_PATH}/admincerts
           mkdir -p ${OUTPUT_PATH}/cacerts
@@ -149,8 +140,8 @@ spec:
             LOOKUP_SECRET_RESPONSE=$(curl -sS \
               --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
               ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-            validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-            PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r ".data.data[\"${vault_data_key}\"]")
+            validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
+            PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r ".data[\"${vault_data_key}\"]")
             echo "${PASSWORD}" >> ${MOUNT_PATH}/user_cred 
           fi            
         volumeMounts:
@@ -214,8 +205,6 @@ spec:
           containerPort: 7051
         - name: events
           containerPort: 7053
-        - name: operations
-          containerPort: 9443
         envFrom:
         - configMapRef:
             name: {{ $.Values.peer.name }}-config
@@ -229,96 +218,20 @@ spec:
         - name: {{ $.Values.peer.name }}-msp-config-volume
           mountPath: /etc/hyperledger/fabric/NodeOUconfig
           readOnly: true
-        resources:
-          requests:
-            memory: {{ .Values.config.pod.resources.requests.memory }}
-            cpu: {{ .Values.config.pod.resources.requests.cpu }}
-          limits:
-            memory: {{ .Values.config.pod.resources.limits.memory }}
-            cpu: {{ .Values.config.pod.resources.limits.cpu }}
-      - name: grpc-web
-        image: "ghcr.io/hyperledger-labs/grpc-web:latest"        
-        ports:
-        - name: grpc-web
-          containerPort: 7443        
-        env:
-        - name: BACKEND_ADDRESS
-          value: "{{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}:{{ $.Values.service.ports.grpc.clusteripport }}"
-        - name: SERVER_TLS_CERT_FILE
-          value: /certs/tls/server.crt
-        - name: SERVER_TLS_KEY_FILE
-          value: /certs/tls/server.key
-        - name: BACKEND_TLS_CA_FILES
-          value: /certs/tls/ca.crt
-        - name: SERVER_BIND_ADDRESS
-          value: "0.0.0.0"
-        - name: SERVER_HTTP_DEBUG_PORT
-          value: "8080"
-        - name: SERVER_HTTP_TLS_PORT
-          value: "7443"
-        - name: BACKEND_TLS
-          value: "true"
-        - name: SERVER_HTTP_MAX_WRITE_TIMEOUT
-          value: 5m
-        - name: SERVER_HTTP_MAX_READ_TIMEOUT
-          value: 5m
-        - name: USE_WEBSOCKETS
-          value: "true"
-        volumeMounts:        
-        - name: certificates
-          mountPath: /certs
-      volumes:
-      {{ if .Values.vault.tls  }}
-      - name: vaultca
-        secret:
-          secretName: {{ $.Values.vault.tls }}
-          items:
-          - key: ca.crt.pem
-            path: ca-certificates.crt
-      {{ end }}
-      - name: certificates
-        emptyDir:
-          medium: Memory
-      - name: dockersocket
-        hostPath:
-          path: /var/run/docker.sock
-      - name: {{ $.Values.peer.name }}-msp-config-volume
-        configMap:
-          name: {{ $.Values.peer.name }}-msp-config
-          items:
-            - key: mspconfig
-              path: mspconfig
-  volumeClaimTemplates:
-  #Lables are not being taken by Kubernetes as it dynamically creates PVC
+  volumeClaimTemplates: 
   - metadata:
       name: datadir
-      annotations:
-        {{- if $.Values.annotations }}
-        {{- range $key, $value := $.Values.annotations.pvc }}
-        {{- range $k, $v := $value }}
-          {{ $k }}: {{ $v | quote }}
-        {{- end }}
-        {{- end }}
-        {{- end }}   
     spec:
+      storageClassName: {{ $.Values.storage.peer.storageclassname }}
       accessModes: [ "ReadWriteOnce" ]
-      storageClassName: {{ .Values.storage.peer.storageclassname }}
       resources:
         requests:
-          storage: {{ .Values.storage.peer.storagesize }}
+          storage: {{ $.Values.storage.peer.storagesize }}
   - metadata:
-      name: datadir-couchdb
-      annotations:
-        {{- if $.Values.annotations }}
-        {{- range $key, $value := $.Values.annotations.pvc }}
-        {{- range $k, $v := $value }}
-          {{ $k }}: {{ $v | quote }}
-        {{- end }}
-        {{- end }}
-        {{- end }}   
+      name: datadir-couchdb     
     spec:
+      storageClassName: {{ $.Values.storage.couchdb.storageclassname }}    
       accessModes: [ "ReadWriteOnce" ]
-      storageClassName: {{ .Values.storage.couchdb.storageclassname }}
       resources:
         requests:
-          storage: {{ .Values.storage.couchdb.storagesize }}
+          storage: {{ $.Values.storage.couchdb.storagesize }}
diff --git a/platforms/hyperledger-fabric/charts/verify_chaincode/templates/verify_chaincode.yaml b/platforms/hyperledger-fabric/charts/verify_chaincode/templates/verify_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/verify_chaincode/templates/verify_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/verify_chaincode/templates/verify_chaincode.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -22,10 +16,6 @@ spec:
     metadata:
       labels:
         app: verifychaincode-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}
-        app.kubernetes.io/name: verifychaincode-{{ $.Values.chaincode.name }}
-        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-        app.kubernetes.io/managed-by: {{ .Release.Service }}
-        app.kubernetes.io/instance: {{ .Release.Name }}
     spec:
       restartPolicy: OnFailure
       serviceAccountName: {{ $.Values.vault.serviceaccountname }}
@@ -46,7 +36,7 @@ spec:
       initContainers:
       - name: certificates-init
         image: {{ $.Values.metadata.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ $.Values.vault.address }}
@@ -65,26 +55,11 @@ spec:
         - |-
           #!/usr/bin/env sh
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
-          
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
           echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
           # Login to Vault and so I can get an approle token
@@ -102,9 +77,9 @@ spec:
             --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
 
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ca.crt"]')
+          TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ca.crt"]')
 
           mkdir -p ${OUTPUT_PATH}
           echo "${TLS_CA_CERT}" >> ${OUTPUT_PATH}/ca.crt
@@ -116,13 +91,13 @@ spec:
           LOOKUP_SECRET_RESPONSE=$(curl -sS  \
             --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
-          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["admincerts"]')
-          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["cacerts"]')
-          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')
-          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["signcerts"]')
-          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlscacerts"]')
+          ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["admincerts"]')
+          CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["cacerts"]')
+          KEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')
+          SIGNCERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["signcerts"]')
+          TLSCACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
           
           mkdir -p ${OUTPUT_PATH}/admincerts
           mkdir -p ${OUTPUT_PATH}/cacerts
@@ -147,7 +122,7 @@ spec:
       containers:
       - name: verifychaincode
         image: {{ $.Values.metadata.images.fabrictools }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         stdin: true
         tty: true
         command: ["sh", "-c"]
@@ -172,7 +147,7 @@ spec:
         - name: CORE_PEER_TLS_ENABLED
           value: "{{ $.Values.peer.tlsstatus }}"
         - name: CORE_PEER_TLS_ROOTCERT_FILE
-          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/tlscacerts/tlsca.crt
+          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/cacerts/ca.crt
         - name: ORDERER_CA
           value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt
         - name: ORDERER_URL
diff --git a/platforms/quorum/charts/node_constellation/templates/deployment.yaml b/platforms/quorum/charts/node_constellation/templates/deployment.yaml
--- a/platforms/quorum/charts/node_constellation/templates/deployment.yaml
+++ b/platforms/quorum/charts/node_constellation/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
@@ -24,11 +18,7 @@ spec:
       app: consortiumchain
       name: {{ .Values.node.name }}
       service.rpc: {{ .Values.node.name }}
-      app.kubernetes.io/name: {{ .Values.node.name }}
-      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-      app.kubernetes.io/managed-by: {{ .Release.Service }}
-      app.kubernetes.io/instance: {{ .Release.Name }} 
-  updateStrategy:
+  strategy:
     type: RollingUpdate
   template:
     metadata:
@@ -37,10 +27,6 @@ spec:
         app: consortiumchain
         name: {{ .Values.node.name }}
         service.rpc: {{ .Values.node.name }}
-        app.kubernetes.io/name: {{ .Values.node.name }}
-        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-        app.kubernetes.io/managed-by: {{ .Release.Service }}
-        app.kubernetes.io/instance: {{ .Release.Name }} 
     spec:
       serviceAccountName: {{ .Values.vault.serviceaccountname }}
       imagePullSecrets:
@@ -55,10 +41,11 @@ spec:
             items:
               - key: genesis.json.base64
                 path: genesis.json.base64
+            
       initContainers:
       - name: certificates-init
         image: {{ .Values.images.alpineutils }}
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
           value: {{ .Values.vault.address }}
@@ -76,24 +63,10 @@ spec:
           #!/usr/bin/env sh
           
           validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
+          if echo ${2} | grep "errors"; then
+           echo "ERROR: unable to retrieve ${1}: ${2}"
+           exit 1
+           fi
           }
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
           echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
@@ -113,12 +86,12 @@ spec:
             --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | \
             jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE" 
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" 
           nodekey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["nodekey"]')
           keystore=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]')
-          geth_password=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["geth_password"]')                    
+          gethpassword=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["gethpassword"]')                    
           
-          echo "${geth_password}" > ${OUTPUT_PATH}/passwords.txt          
+          echo "${gethpassword}" > ${OUTPUT_PATH}/passwords.txt          
           echo "${nodekey}" > ${OUTPUT_PATH}/nodekey
           echo "${keystore}" > ${OUTPUT_PATH}/{{ .Values.node.keystore }}
 
@@ -128,7 +101,7 @@ spec:
             --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | \
             jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE" 
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
 
           tmpub=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tm.pub"]')
           tmkey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tm.key"]')
@@ -203,7 +176,7 @@ spec:
         - |-
           #!/usr/bin/env sh
           apk add curl;
-          echo -n {{ .Values.staticnodes | toRawJson | quote }} > $QUORUM_DATA_DIR/static-nodes.json
+          echo -n {{ .Values.staticnodes | toJson | quote }} > $QUORUM_DATA_DIR/static-nodes.json
           mkdir -p $QUORUM_DATA_DIR/geth
           mkdir -p $QUORUM_DATA_DIR/keystore          
           # touch $qd/passwords.txt
diff --git a/platforms/r3-corda-ent/charts/float/templates/deployment.yaml b/platforms/r3-corda-ent/charts/float/templates/deployment.yaml
--- a/platforms/r3-corda-ent/charts/float/templates/deployment.yaml
+++ b/platforms/r3-corda-ent/charts/float/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 ---  
 apiVersion: apps/v1
 kind: Deployment
@@ -40,7 +34,7 @@ spec:
         fsGroup: 1000
       initContainers:
       - name: init-certificates
-        image: {{ .Values.image.initContainerName }}
+        image: {{ .Values.initContainerImage.name }}
         imagePullPolicy: Always
         env:
           - name: VAULT_ADDR
@@ -53,31 +47,19 @@ spec:
             value: {{ $.Values.volume.baseDir }}
           - name: CERTS_SECRET_PREFIX
             value: {{ .Values.vault.certsecretprefix }}
+          - name: MOUNT_PATH
+            value: "/DATA"
         command: ["sh", "-c"]
         args:
         - |-
               #!/usr/bin/env sh
               validateVaultResponse () {
                 if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code and curl_response - $curl_response"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
+                    echo "ERROR: unable to retrieve ${1}: ${2}"
+                    exit 1
                 fi
               }
-
+              
               # setting up env to get secrets from vault
               echo "Getting secrets from Vault Server"
               KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
@@ -85,141 +67,122 @@ spec:
               validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
               echo "logged into vault"
 
-              OUTPUT_PATH=${BASE_DIR}/certificates
+              # Creating directory for storing certificates
+              mkdir -p /shared/certificates;
+              
+              # Fetching SSL Keystore certificate from vault
+              COUNTER=1
+              while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
+              do
+                  # get keystores from vault to see if certificates are created and put in vault
+                  LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/root/certs | jq -r 'if .errors then . else . end')
+                  if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
+                  then
+                    sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+                  else
+                    ssl_keystore=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["root-key-store.jks"]')
+                    echo "${ssl_keystore}" | base64 -d > /shared/certificates/sslkeystore.jks
+                    echo "Successfully got SSL Keystore certifcate"
+                    break
+                  fi
+                  COUNTER=`expr "$COUNTER" + 1`
+              done
 
-              # get sslkeystore.jks from vault
-              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/sslkeystore | jq -r 'if .errors then . else . end')
-              validateVaultResponse "{CERTS_SECRET_PREFIX}/certs/sslkeystore" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-              TLS_SSLKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["sslkeystore.jks"]')
-              echo "${TLS_SSLKEYSTORE}" | base64 -d > ${OUTPUT_PATH}/sslkeystore.jks
-
-              # get truststore.jks from vault
-              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/truststore | jq -r 'if .errors then . else . end')
-              validateVaultResponse "${CERTS_SECRET_PREFIX}/certs/truststore" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-              TLS_TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["truststore.jks"]')
-              echo "${TLS_TRUSTSTORE}" | base64 -d > ${OUTPUT_PATH}/truststore.jks              
+              if [ "$COUNTER" -ge {{ $.Values.healthcheck.readinessthreshold }} ]
+              then
+                # printing number of trial done before giving up
+                echo "SSL Keystore certificates might not have been put in Vault. Giving up after $COUNTER tries!"
+                exit 1s
+              fi
               echo "Done"
-              
-              # Fetching float Certificate from vault
-              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/firewall | jq -r 'if .errors then . else . end')
-              validateVaultResponse "${CERTS_SECRET_PREFIX}/certs/firewall" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-              float=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["float.jks"]')
-              echo "${float}" | base64 -d > ${OUTPUT_PATH}/float.jks
-              echo "Successfully got Bridge Certifcate"
 
-              trust=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["trust.jks"]')
-              echo "${trust}" | base64 -d > ${OUTPUT_PATH}/trust.jks
-              echo "Successfully got trust Certifcate"
-              
-              # Fetching node keystore, node truststore and network-root-truststore credentials from vault
-              mkdir -p ${OUTPUT_PATH}/credentials
-              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/credentials | jq -r 'if .errors then . else . end')
-              validateVaultResponse "${CERTS_SECRET_PREFIX}/credentials" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-              TRUSTSTORE_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["truststore"]')
-              echo "${TRUSTSTORE_PASSWORD}" > ${OUTPUT_PATH}/credentials/truststorepass
-              KEYSTORE_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["keystore"]')
-              echo "${KEYSTORE_PASSWORD}" > ${OUTPUT_PATH}/credentials/keystorepass  
-              FIREWALL_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["firewallca"]')
-              echo "${FIREWALL_PASSWORD}" > ${OUTPUT_PATH}/credentials/firewallpass
-              FLOAT_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["float"]')
-              echo "${FLOAT_PASSWORD}" > ${OUTPUT_PATH}/credentials/floatpass
+              # Fetching Float Certificate from vault
+              COUNTER=1
+              while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
+              do
+                  # get keystores from vault to see if certificates are created and put in vault
+                  LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/root/certs | jq -r 'if .errors then . else . end')
+                  if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
+                  then
+                    sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+                  else
+                    float=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["float.jks"]')
+                    echo "${float}" | base64 -d > /shared/certificates/float.jks
+                    echo "Successfully got Float Certifcate"
+                    break
+                  fi
+                  COUNTER=`expr "$COUNTER" + 1`
+              done
+
+              if [ "$COUNTER" -ge {{ $.Values.healthcheck.readinessthreshold }} ]
+              then
+                # printing number of trial done before giving up
+                echo "Float certificate might not have been put in Vault. Giving up after $COUNTER tries!"
+                exit 1s
+              fi
               echo "Done"
-              
-              # TODO: Get network-parameters from corresponding Node
-              echo "Done with init-certificates..."             
+
+              # Fetching corda-ssl-trust-store certificates from vault
+              COUNTER=1
+              while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
+              do
+                  # get keystores from vault to see if certificates are created and put in vault
+                  LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/root/certs | jq -r 'if .errors then . else . end')
+                  if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
+                  then
+                    sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+                  else
+                    root_ssl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["corda-ssl-trust-store.jks"]')
+                    echo "${root_ssl}" | base64 -d > /shared/certificates/truststore.jks
+                    root_trust=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["network-root-truststore.jks"]')
+                    echo "${root_trust}" | base64 -d > /shared/certificates/trust.jks
+
+                    echo "Successfully got Root SSL and Truststore certifcates"
+                    break
+                  fi
+                  COUNTER=`expr "$COUNTER" + 1`
+              done
+
+              if [ "$COUNTER" -ge {{ $.Values.healthcheck.readinessthreshold }} ]
+              then
+                # Printing number of trials done before giving up
+                echo "Root SSL or Truststore certificates might not have been put in Vault. Giving up after $COUNTER tries!"
+                exit 1
+              fi
+              # The general Firewall Docker image checks the existence network-parameters,
+              # both on Bridge + Float in it's startFirewall.sh script;
+              # while it is only required for Bridge. So, we have to create a dummy file to make the script work.
+              echo dummy_file > /shared/network-parameters
+              echo "Done"              
         volumeMounts:
         - name: certificates
-          mountPath: {{ $.Values.volume.baseDir }}/certificates
+          mountPath: /shared
       imagePullSecrets:
-      - name: {{ .Values.image.imagePullSecret }}
+      - name: {{ .Values.image.pullSecret }}
       containers:
       - name: main
-        image: "{{ .Values.image.mainContainerName }}"
+        image: "{{ required "float[main]: missing value for .Values.image.name" .Values.image.name }}"
         imagePullPolicy: {{ .Values.image.pullPolicy }}
-        env:
-          - name: BASE_DIR
-            value: {{ $.Values.volume.baseDir }}
-        command: ["sh", "-c"]
-        args:
-        - |-
-          echo 'firewallMode: FloatOuter
-          networkParametersPath: "network-parameters"
-          
-          inboundConfig: {
-            listeningAddress: "{{ .Values.dmz.external }}:{{ .Values.node.p2pPort }}"
-          }
-          
-          floatOuterConfig: {
-              floatAddress: "{{ .Values.dmz.internal }}:{{ .Values.bridge.tunnelPort }}"
-              expectedCertificateSubject: "{{ .Values.bridge.subject }}"
-              tunnelSSLConfiguration: {
-                     keyStorePassword: "FLOAT_PASSWORD"
-                     trustStorePassword: "FIREWALL_PASSWORD"
-                     sslKeystore: "certificates/float.jks"
-                     trustStoreFile: "certificates/trust.jks"
-              }
-          }
-          
-          revocationConfig: { mode: "EXTERNAL_SOURCE"}
-          
-          certificatesDirectory: "certificates"
-          sslKeystore: "certificates/sslkeystore.jks"
-          trustStoreFile: "certificates/truststore.jks"
-          keyStorePassword: "KEYSTORE_PASSWORD"
-          trustStorePassword: "TRUSTSTORE_PASSWORD"
-          silencedIPs: []
-          
-          enableAMQPPacketTrace: true
-          artemisReconnectionIntervalMin: 5000
-          artemisReconnectionIntervalMax: 60000
-          politeShutdownPeriod: 1000
-          p2pConfirmationWindowSize: 1048576
-          auditServiceConfiguration: {
-            loggingIntervalSec: 60
-          }' >> ${BASE_DIR}/firewall.conf
-
-          export TRUSTSTORE_PASSWORD=$(cat ${BASE_DIR}/certificates/credentials/truststorepass)
-          sed -i -e "s*TRUSTSTORE_PASSWORD*${TRUSTSTORE_PASSWORD}*g" ${BASE_DIR}/firewall.conf
-          export KEYSTORE_PASSWORD=$(cat ${BASE_DIR}/certificates/credentials/keystorepass)
-          sed -i -e "s*KEYSTORE_PASSWORD*${KEYSTORE_PASSWORD}*g" ${BASE_DIR}/firewall.conf
-          export FIREWALL_PASSWORD=$(cat ${BASE_DIR}/certificates/credentials/firewallpass)
-          sed -i -e "s*FIREWALL_PASSWORD*${FIREWALL_PASSWORD}*g" ${BASE_DIR}/firewall.conf
-          export FLOAT_PASSWORD=$(cat ${BASE_DIR}/certificates/credentials/floatpass)
-          sed -i -e "s*FLOAT_PASSWORD*${FLOAT_PASSWORD}*g" ${BASE_DIR}/firewall.conf
-          
-          ifNetworkParametersExists () {                                                                                                                            
-              if [ -f ${BASE_DIR}/network-parameters ]
-              then                                                                                                                                                     
-                  return 1                                                                                                                                             
-              else                                                                                                                                                     
-                  return 0                                                                                                                                             
-              fi                                                                                                                                                       
-          }  
-          let EXIT_CODE=0                                                                                                                                      
-          while [ ${EXIT_CODE} -eq 0 ]                                                                                                                         
-          do
-                  sleep 2                                                                                                             
-                  echo "Checking for network parameters"
-                  ifNetworkParametersExists
-                  let EXIT_CODE=$?
-          done
-
-          echo "Starting the firewall"                                                                                                                                         
-          java -jar corda-firewall.jar --base-directory ${BASE_DIR} --verbose --logging-level=INFO 
         resources:
           requests:
             memory: {{ .Values.cordaJarMx }}M
           limits:
             memory: {{ add .Values.cordaJarMx 2}}M
         volumeMounts:
-        - name: float-volume
-          mountPath: {{ .Values.volume.baseDir }}
         - name: certificates
-          mountPath: {{ .Values.volume.baseDir }}/certificates
+          mountPath: /opt/corda/workspace/
+        - name: float-conf
+          mountPath: /opt/corda/workspace/firewall.conf
+          subPath: firewall.conf
+        - name: float-logs
+          mountPath: /opt/corda/workspace/logs
       volumes:
         - name: certificates
           emptyDir:
             medium: Memory
-        - name: float-volume
+        - name: float-conf
+          configMap:
+            name: {{ .Values.nodeName }}-conf
+        - name: float-logs
           persistentVolumeClaim:
-            claimName: {{ .Values.nodeName }}-volume
+            claimName: {{ .Values.nodeName }}-pvc-logs
diff --git a/platforms/r3-corda-ent/charts/idman/templates/deployment.yaml b/platforms/r3-corda-ent/charts/idman/templates/deployment.yaml
--- a/platforms/r3-corda-ent/charts/idman/templates/deployment.yaml
+++ b/platforms/r3-corda-ent/charts/idman/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 ---
 apiVersion: apps/v1
 kind: Deployment
@@ -40,7 +34,7 @@ spec:
         fsGroup: 1000
       initContainers:      
       - name: init-certificates
-        image: "{{ .Values.image.initContainer }}"
+        image: "{{ required "idman[config]: missing value for .Values.image.initContainerName" .Values.image.initContainerName }}"
         imagePullPolicy: {{ .Values.image.pullPolicy }}
         env:
           - name: VAULT_ADDR
@@ -61,22 +55,8 @@ spec:
               #!/usr/bin/env sh
               validateVaultResponse () {
                 if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code and curl_response - $curl_response"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
+                   echo "ERROR: unable to retrieve ${1}: ${2}"
+                   exit 1
                 fi
               }
 
@@ -86,12 +66,10 @@ spec:
               VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
               validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
               echo "Logged into Vault"
-              # Creating dirs for storing certificates and credentials
+              # Creating dirs for storing certificates
               mkdir -p ${MOUNT_PATH}/idman;
               mkdir -p ${MOUNT_PATH}/root;
               mkdir -p ${MOUNT_PATH}/crl-files;
-              mkdir -p ${MOUNT_PATH}/ssl;
-              mkdir -p ${MOUNT_PATH}/truststore;
 
               # Fetching ssl-idman certificates from vault
               COUNTER=1
@@ -99,14 +77,11 @@ spec:
               do
                   # Get keystores from Vault, to see if certificates are created and have been put in Vault
                   LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/certs | jq -r 'if .errors then . else . end')
-                  data_info="$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["data"]')"
-              
-                  if [ "$data_info" == "null" ]
+                  if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
                   then
                     sleep {{ $.Values.vault.sleepTimeAfterError }}
                   else
-                    validateVaultResponse "${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/certs" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-                    idm_ssl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["corda-ssl-identity-manager-keys.jks"]')
+                    idm_ssl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["corda-ssl-identity-manager-keys.jks"]')
                     echo "${idm_ssl}" | base64 -d > ${MOUNT_PATH}/idman/corda-ssl-identity-manager-keys.jks
                     echo "Successfully got SSL Idman certifcates"
                     break
@@ -127,14 +102,11 @@ spec:
               do
                   # Get keystores from Vault, to see if certificates are created and have been put in Vault
                   LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/root/certs | jq -r 'if .errors then . else . end')
-                  data_info="$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["data"]')"
-              
-                  if [ "$data_info" == "null" ]
+                  if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
                   then
                     sleep {{ $.Values.vault.sleepTimeAfterError }}
                   else
-                    validateVaultResponse "${CERTS_SECRET_PREFIX}/root/certs" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-                    root_ssl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["corda-ssl-trust-store.jks"]')
+                    root_ssl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["corda-ssl-trust-store.jks"]')
                     echo "${root_ssl}" | base64 -d > ${MOUNT_PATH}/root/corda-ssl-trust-store.jks
                     echo "Successfully got Root SSL certifcates"
                     break
@@ -155,20 +127,17 @@ spec:
               do
                   # Get CRLs from vault to see if certificates are created, and have been put in Vault
                   LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ .Values.nodeName }}/crls | jq -r 'if .errors then . else . end')
-                  data_info="$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["data"]')"
-              
-                  if [ "$data_info" == "null" ]
+                  if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
                   then
                     sleep {{ $.Values.vault.sleepTimeAfterError }}
                   else
-                    validateVaultResponse "${CERTS_SECRET_PREFIX}/{{ .Values.nodeName }}/crls" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-                    tls_crl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tls.crl"]')
+                    tls_crl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tls.crl"]')
                     echo "${tls_crl}" | base64 -d > ${MOUNT_PATH}/crl-files/tls.crl
 
-                    root_crl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["root.crl"]')
+                    root_crl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["root.crl"]')
                     echo "${root_crl}" | base64 -d > ${MOUNT_PATH}/crl-files/root.crl
 
-                    subordinate_crl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["subordinate.crl"]')
+                    subordinate_crl=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["subordinate.crl"]')
                     echo "${subordinate_crl}" | base64 -d > ${MOUNT_PATH}/crl-files/subordinate.crl
 
                     echo "Successfully got CRL Certifcates"
@@ -182,135 +151,13 @@ spec:
                 echo "CRL Certificates might not have been put in Vault. Giving up after $COUNTER tries!"
                 exit 1
               fi
-
-              # Fetching the idman ssl credentials from vault
-              OUTPUT_PATH=${MOUNT_PATH}/ssl;
-              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/credentials/ssl | jq -r 'if .errors then . else . end')
-              validateVaultResponse "${CERTS_SECRET_PREFIX}/credentials/ssl" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-              IDMAN_SSL=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["idman"]')
-              echo "${IDMAN_SSL}"> ${OUTPUT_PATH}/idmanssl
-
-              #Fetching ssl truststore from vault
-              OUTPUT_PATH=${MOUNT_PATH}/truststore;
-              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/credentials/truststore | jq -r 'if .errors then . else . end')
-              validateVaultResponse "${CERTS_SECRET_PREFIX}/credentials/truststore" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-              SSL_TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["ssl"]')
-              echo "${SSL_TRUSTSTORE}"> ${OUTPUT_PATH}/sslts
-
               echo "Done"
         volumeMounts:
         - name: certificates
-          mountPath: /DATA    
-      - name: init-token
-        image: "{{ .Values.image.enterpriseCliContainer }}"
-        imagePullPolicy: {{ .Values.image.pullPolicy }}
-        env:
-          - name: ACCEPT_LICENSE
-            value: "{{ .Values.acceptLicense }}"
-        command: ["/bin/bash", "-c"]
-        args:
-        - |-
-          pwd
-          cp CM/*.sh bin/
-          chmod +x bin/*
-          ls -alR
-          echo 'address = "0.0.0.0:{{ .Values.service.external.port }}"
-          database {
-              driverClassName = "{{ .Values.database.driverClassName }}"
-              url = "{{ .Values.database.url }}"
-              user = "{{ .Values.database.user }}"
-              password = "{{ .Values.database.password }}"
-              runMigration = "{{ .Values.database.runMigration }}"
-          }
-          workflows = {
-              "identity-manager" = {
-                  type = ISSUANCE
-                  updateInterval = 10000
-                  enmListener = {
-                      port = {{ .Values.service.internal.port }}
-                      reconnect = true
-                      ssl = {
-                          keyStore = {
-                              location = ./DATA/idman/corda-ssl-identity-manager-keys.jks
-                              password = IDMAN_SSL
-                          }
-                          trustStore = {
-                              location = ./DATA/root/corda-ssl-trust-store.jks
-                              password = SSL_TRUSTSTORE
-                          }
-                      }
-                  }
-                  plugin = {
-                      pluginClass = "com.r3.enmplugins.approveall.ApproveAll"
-                  }
-              },
-              "revocation" = {
-                  type = REVOCATION
-                  crlCacheTimeout = 900000 # every 15 minutes
-                  crlFiles = ["./DATA/crl-files/tls.crl", "./DATA/crl-files/root.crl", "./DATA/crl-files/subordinate.crl"]
-                  enmListener = {
-                      port = {{ .Values.service.revocation.port }}
-                      reconnect = true
-                      ssl = {
-                          keyStore = {
-                              location = ./DATA/idman/corda-ssl-identity-manager-keys.jks
-                              password = IDMAN_SSL
-                          }
-                          trustStore = {
-                              location = ./DATA/root/corda-ssl-trust-store.jks
-                              password = SSL_TRUSTSTORE
-                          }
-                      }
-                  }
-                  plugin = {
-                      pluginClass = "com.r3.enmplugins.approveall.ApproveAll"
-                  }
-              }
-          }
-          authServiceConfig = {
-              disableAuthentication=false
-              host="{{ .Values.cenmServices.authName }}.{{ .Values.metadata.namespace }}"
-              port={{ .Values.cenmServices.authPort }}
-              trustStore = {
-                  location = "./DATA/root/corda-ssl-trust-store.jks"
-                  password = SSL_TRUSTSTORE
-              }
-              issuer="http://test"
-              leeway=5s
-          }
-          adminListener = {
-              port = {{ .Values.service.adminListener.port }}
-              ssl = {
-                  keyStore = {
-                      location = ./DATA/idman/corda-ssl-identity-manager-keys.jks
-                      password = IDMAN_SSL
-                  }
-                  trustStore = {
-                      location = ./DATA/root/corda-ssl-trust-store.jks
-                      password = SSL_TRUSTSTORE
-                  }
-              }
-          }' >> etc/idman.conf
-
-          #replacing the variables in idman.conf with actual values
-          export IDMAN_SSL=$(cat {{ .Values.config.volume.baseDir }}/DATA/ssl/idmanssl)
-          sed -i -e "s*IDMAN_SSL*${IDMAN_SSL}*g" etc/idman.conf
-          export SSL_TRUSTSTORE=$(cat {{ .Values.config.volume.baseDir }}/DATA/truststore/sslts)
-          sed -i -e "s*SSL_TRUSTSTORE*${SSL_TRUSTSTORE}*g" etc/idman.conf
-          bin/getZoneToken.sh
-        resources:
-          {{- toYaml .Values.resources | nindent 12 }}
-        volumeMounts:
-        - name: idman-etc
-          mountPath: {{ .Values.config.volume.baseDir }}/etc
-        - name: idman-conf
-          mountPath: {{ .Values.config.volume.baseDir }}/CM/getZoneToken.sh
-          subPath: getZoneToken.sh
-        - name: certificates
-          mountPath: {{ .Values.config.volume.baseDir }}/DATA 
+          mountPath: /DATA            
       containers:
       - name: idman
-        image: "{{ .Values.image.idmanContainer }}"
+        image: "{{ required "idman[idman]: missing value for .Values.image.idmanContainerName" .Values.image.idmanContainerName }}"
         imagePullPolicy: {{ .Values.image.pullPolicy }}
         env:
           - name: ACCEPT_LICENSE
@@ -318,66 +165,28 @@ spec:
         command: ["/bin/bash", "-c"]
         args:
         - |-
-          #running the idman service
-          /bin/sh
-          #main run
-          export IDMAN_SSL=$(cat {{ .Values.config.volume.baseDir }}/DATA/ssl/idmanssl)
-          export SSL_TRUSTSTORE=$(cat {{ .Values.config.volume.baseDir }}/DATA/truststore/sslts)
-          if [ -f {{ .Values.config.jarPath }}/identitymanager.jar ]
-          then
-              sha256sum {{ .Values.config.jarPath }}/identitymanager.jar
-              sha256sum {{ .Values.config.jarPath }}/angel.jar
-              cp {{ .Values.config.configPath }}/idman.conf {{ .Values.config.configPath }}/identitymanager.conf
-              cat {{ .Values.config.configPath }}/identitymanager.conf
-              echo
-              echo "CENM: starting Identity Manager process ..."
-              echo
-              java -jar {{ .Values.config.jarPath }}/angel.jar \
-              --jar-name={{ .Values.config.jarPath }}/identitymanager.jar \
-              --zone-host={{ .Values.cenmServices.zoneName }}.{{ .Values.metadata.namespace }} \
-              --zone-port={{ .Values.cenmServices.zoneEnmPort }} \
-              --token=${TOKEN} \
-              --service=IDENTITY_MANAGER \
-              --working-dir=etc/ \
-              --polling-interval=10 \
-              --tls=true \
-              --tls-keystore={{ .Values.config.volume.baseDir }}/DATA/idman/corda-ssl-identity-manager-keys.jks \
-              --tls-keystore-password=${IDMAN_SSL} \
-              --tls-truststore={{ .Values.config.volume.baseDir }}/DATA/root/corda-ssl-trust-store.jks \
-              --tls-truststore-password=${SSL_TRUSTSTORE} \
-              --verbose
-              EXIT_CODE=${?}
-          else
-              echo "Missing Identity Manager jar file in {{ .Values.config.jarPath }} folder:"
-              ls -al {{ .Values.config.jarPath }}
-              EXIT_CODE=110
-          fi
-
-          if [ "${EXIT_CODE}" -ne "0" ]
-          then
-              HOW_LONG={{ .Values.config.sleepTimeAfterError }}
-              echo
-              echo "exit code: ${EXIT_CODE} (error)"
-              echo "Going to sleep for requested ${HOW_LONG} seconds to let you login and investigate."
-          fi
-          sleep ${HOW_LONG}
-          echo
+          cp CM/run.sh bin/
+          cp CM/idman.conf etc/
+          chmod +x bin/*
+          bin/run.sh
         volumeMounts:
         - name: idman-etc
-          mountPath: {{ .Values.config.volume.baseDir }}/etc
+          mountPath: /opt/corda/etc
+        - name: idman-conf
+          mountPath: /opt/corda/CM
         - name: idman-logs
-          mountPath: {{ .Values.config.volume.baseDir }}/logs
+          mountPath: /opt/corda/logs
         - name: idman-h2
-          mountPath: {{ .Values.config.volume.baseDir }}/h2
+          mountPath: /opt/corda/h2
         - name: certificates
-          mountPath: {{ .Values.config.volume.baseDir }}/DATA
+          mountPath: /opt/corda/DATA
         resources:
           requests:
             memory: {{ .Values.config.pod.resources.requests}}
           limits:
             memory: {{ .Values.config.pod.resources.limits}}
       - name: logs
-        image: "{{ .Values.image.idmanContainer }}"
+        image: "{{ required "idman[logs]: missing value for .Values.image.idmanContainerName" .Values.image.idmanContainerName }}"
         imagePullPolicy: {{ .Values.image.pullPolicy }}
         env:
         - name: ACCEPT_LICENSE
@@ -385,21 +194,19 @@ spec:
         command: ["/bin/bash", "-c"]
         args:
         - |-
-          cd {{ .Values.config.volume.baseDir }}
-          while true; do tail -f logs/angel-service/*.log 2>/dev/null; sleep 5; done
+          cd /opt/corda
+          while true; do tail -f logs/identity-manager/*.log 2>/dev/null; sleep 5; done
           # in case sth went wrong just wait indefinitely ...
           tail -f /dev/null
         volumeMounts:
         - name: idman-logs
-          mountPath: {{ .Values.config.volume.baseDir }}/logs
-    {{- with .Values.image.imagePullSecrets }}
+          mountPath: /opt/corda/logs
       imagePullSecrets:
-        {{- toYaml . | nindent 8 }}
-    {{- end }}
+      - name: {{ .Values.image.imagePullSecret }}
       volumes:
         - name: idman-conf
           configMap:
-            name: {{ .Values.prefix }}-idman-conf
+            name: {{ .Values.nodeName }}-conf
         - name: idman-etc
           emptyDir:
             medium: Memory
diff --git a/platforms/r3-corda/charts/doorman/templates/deployment.yaml b/platforms/r3-corda/charts/doorman/templates/deployment.yaml
--- a/platforms/r3-corda/charts/doorman/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/doorman/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 # Deployment
 # Creates the replicated container and manages lifecycle
 # TLS certs mounted
@@ -89,26 +83,12 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-              validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
-                fi
-              }
+             validateVaultResponse () {
+             if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+              fi
+             }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
@@ -119,13 +99,13 @@ spec:
 
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.certsecretprefix }} | jq -r 'if .errors then . else . end')
 
-             validateVaultResponse "{{ .Values.vault.certsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+             validateVaultResponse "secret ({{ .Values.vault.certsecretprefix }})" "${LOOKUP_SECRET_RESPONSE}"
 
-             ROOTCA_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["rootcakey"]')
+             ROOTCA_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["rootcakey"]')
              mkdir -p ${OUTPUT_PATH}/root;
              echo "${ROOTCA_KEY}" | base64 -d > ${OUTPUT_PATH}/root/keys.jks
 
-             DOORMAN_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["doorman.jks"]')
+             DOORMAN_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["doorman.jks"]')
              mkdir -p ${OUTPUT_PATH}/doorman;
              echo "${DOORMAN_KEY}" | base64 -d > ${OUTPUT_PATH}/doorman/keys.jks
              chmod 777 -R {{ .Values.image.mountPath.basePath }}/db
@@ -155,26 +135,12 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-              validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
-                fi
-              }
+             validateVaultResponse () {
+             if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+              fi
+             }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
@@ -183,16 +149,14 @@ spec:
              echo "logged into vault"
              OUTPUT_PATH=${MOUNT_PATH}
              LOOKUP_PWD_RESPONSE_DB_PASS=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${DB_CRED_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-
-             validateVaultResponse "${DB_CRED_SECRET_PREFIX}" "${LOOKUP_PWD_RESPONSE_DB_PASS}" "LOOKUPSECRETRESPONSE"
              
-             MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE_DB_PASS} | jq -r '.data.data["mongodbPassword"]')
+             MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE_DB_PASS} | jq -r '.data["mongodbPassword"]')
              echo "${MONGODB_PASSWORD}" >> ${MOUNT_PATH}/db_root_password
              cat ${MOUNT_PATH}/db_root_password
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${USER_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-             validateVaultResponse "${USER_SECRET_PREFIX}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+             validateVaultResponse "secret (${CERTS_SECRET_PREFIX})" "${LOOKUP_SECRET_RESPONSE}"
              
-             USER_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["{{ .Values.image.authusername }}"]')
+             USER_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["{{ .Values.image.authusername }}"]')
              echo "${USER_PASSWORD}" >> ${MOUNT_PATH}/user_cred
              
         volumeMounts:
diff --git a/platforms/r3-corda/charts/mongodb-tls/templates/deployment.yaml b/platforms/r3-corda/charts/mongodb-tls/templates/deployment.yaml
--- a/platforms/r3-corda/charts/mongodb-tls/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/mongodb-tls/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -40,7 +34,7 @@ spec:
         command:
         - /bin/sh
         - -c
-        - >          
+        - >
           if [ -f /data/db/admin-user.lock ]; then
           #file /data/db/admin-user.lock created and checked to ensure mongod is fully up for adding new db user in postStart hook.
             echo "KUBERNETES LOG $HOSTNAME- Starting Mongo Daemon"
@@ -89,7 +83,7 @@ spec:
           readOnly: false
         - name: certs
           mountPath: "/etc/ssl"
-          readOnly: false
+          readonly: false  
       initContainers:
       - name: init-credential
         image : {{ .Values.image.initContainerName }}
@@ -114,24 +108,10 @@ spec:
         - |-
            #!/usr/bin/env sh
             validateVaultResponse () {
-              if echo ${2} | grep "errors"; then
-                echo "ERROR: unable to retrieve ${1}: ${2}"
-                exit 1
-              fi
-              if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-              then
-                http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                ${VAULT_ADDR}/v1/${1})
-                curl_response=$?
-                if test "$http_code" != "200" ; then
-                    echo "Http response code from Vault - $http_code"
-                    if test "$curl_response" != "0"; then
-                      echo "Error: curl command failed with error code - $curl_response"
-                      exit 1
-                    fi
-                fi
-              fi
+            if echo ${2} | grep "errors"; then
+             echo "ERROR: unable to retrieve ${1}: ${2}"
+             exit 1
+             fi
             }
             echo "Getting secrets from Vault Server"
            
@@ -141,11 +121,7 @@ spec:
 
             OUTPUT_PATH=${MOUNT_PATH}
             LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-
-            validateVaultResponse "${SECRET_PREFIX}" "${LOOKUP_PWD_RESPONSE}" "LOOKUPSECRETRESPONSE"
-
-
-            MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["mongodbPassword"]')
+            MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["mongodbPassword"]')
             
             echo "${MONGODB_PASSWORD}" >> ${MOUNT_PATH}/db_root_password
             echo "${MONGODB_USERNAME}" >> ${MOUNT_PATH}/db_root_username
@@ -153,14 +129,14 @@ spec:
             LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERT_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
             
             # Validating vault response for mongodb certificates. 
-            validateVaultResponse "${CERT_SECRET_PREFIX}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+            validateVaultResponse "secret ${CERT_SECRET_PREFIX}" "${LOOKUP_SECRET_RESPONSE}"
             
             # Getting certificates of server from vault and storing into /etc/ssl.
-            SERVER_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["{{ $.Values.nodeName }}.pem"]')
+            SERVER_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["{{ $.Values.nodeName }}.pem"]')
             echo "${SERVER_CERT}" | base64 -d > /etc/ssl/{{ $.Values.nodeName }}.pem
                         
             # Getting certificate authority cert from vault which is required for client validation and storing into /etc/ssl.
-            CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["mongoCA.crt"]')
+            CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["mongoCA.crt"]')
             echo "${CA_CERT}" | base64 -d > /etc/ssl/mongoCA.crt
         volumeMounts:
           - name: creds
diff --git a/platforms/r3-corda/charts/mongodb/templates/deployment.yaml b/platforms/r3-corda/charts/mongodb/templates/deployment.yaml
--- a/platforms/r3-corda/charts/mongodb/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/mongodb/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -67,24 +61,10 @@ spec:
         - |-
            #!/usr/bin/env sh
             validateVaultResponse () {
-              if echo ${2} | grep "errors"; then
-                echo "ERROR: unable to retrieve ${1}: ${2}"
-                exit 1
-              fi
-              if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-              then
-                http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                ${VAULT_ADDR}/v1/${1})
-                curl_response=$?
-                if test "$http_code" != "200" ; then
-                    echo "Http response code from Vault - $http_code"
-                    if test "$curl_response" != "0"; then
-                      echo "Error: curl command failed with error code - $curl_response"
-                      exit 1
-                    fi
-                fi
-              fi
+            if echo ${2} | grep "errors"; then
+             echo "ERROR: unable to retrieve ${1}: ${2}"
+             exit 1
+             fi
             }
             echo "Getting secrets from Vault Server"
            
@@ -94,10 +74,7 @@ spec:
 
             OUTPUT_PATH=${MOUNT_PATH}
             LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-
-            validateVaultResponse "${SECRET_PREFIX}" "${LOOKUP_PWD_RESPONSE}" "LOOKUPSECRETRESPONSE"
-
-            MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["mongodbPassword"]')
+            MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["mongodbPassword"]')
             
             echo "${MONGODB_PASSWORD}" >> ${MOUNT_PATH}/db_root_password
             echo "${MONGODB_USERNAME}" >> ${MOUNT_PATH}/db_root_username
diff --git a/platforms/r3-corda/charts/nms-tls/templates/deployment.yaml b/platforms/r3-corda/charts/nms-tls/templates/deployment.yaml
--- a/platforms/r3-corda/charts/nms-tls/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/nms-tls/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 # Deployment
 # Creates the replicated container and manages lifecycle
 # TLS certs mounted
@@ -44,7 +38,6 @@ spec:
       containers:
       - name: {{ .Values.nodeName }}-service
         image: {{ .Values.image.containerName }}
-        imagePullPolicy: Always
         command: ["sh", "-c"]
         args:
         - |-
@@ -102,26 +95,12 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-              validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
-                fi
-              }
+             validateVaultResponse () {
+             if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+              fi
+             }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
@@ -132,13 +111,13 @@ spec:
 
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.certsecretprefix }} | jq -r 'if .errors then . else . end')
 
-             validateVaultResponse "${{ .Values.vault.certsecretprefix }})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+             validateVaultResponse "secret (${{ .Values.vault.certsecretprefix }})" "${LOOKUP_SECRET_RESPONSE}"
 
-             ROOTCA_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["rootcakey"]')
+             ROOTCA_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["rootcakey"]')
              mkdir -p ${OUTPUT_PATH}/root;
              echo "${ROOTCA_KEY}" | base64 -d > ${OUTPUT_PATH}/root/keys.jks
              
-             NETWORKMAP_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["networkmap.jks"]')
+             NETWORKMAP_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["networkmap.jks"]')
              mkdir -p ${OUTPUT_PATH}/network-map;
              echo "${NETWORKMAP_KEY}" | base64 -d > ${OUTPUT_PATH}/network-map/keys.jks
              
@@ -165,26 +144,12 @@ spec:
         args:
         - |-
           #!/usr/bin/env sh
-              validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
-                fi
-              }
+          validateVaultResponse () {
+            if echo ${2} | grep "errors"; then
+               echo "ERROR: unable to retrieve ${1}: ${2}"
+               exit 1
+            fi
+          }
           
           # setting up env to get secrets from vault   
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
@@ -199,9 +164,9 @@ spec:
           then                
              # get networkmap tls cert and key from vault
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.tlscertsecretprefix }} | jq -r 'if .errors then . else . end')            
-             validateVaultResponse "${{ .Values.vault.tlscertsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"          
-             NETWORKMAP_CRT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlscacerts"]')
-             NETWORKMAP_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["tlskey"]')
+             validateVaultResponse "secret (${{ .Values.vault.tlscertsecretprefix }})" "${LOOKUP_SECRET_RESPONSE}"           
+             NETWORKMAP_CRT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
+             NETWORKMAP_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlskey"]')
              echo "check-1 $NETWORKMAP_CRT"
              echo "check-2 $NETWORKMAP_KEY"
              echo "${NETWORKMAP_CRT}" | base64 -d > {{ .Values.image.mountPath.basePath }}-tls/certs/networkmap.crt 
@@ -210,8 +175,10 @@ spec:
           
           # get mongo tls cert from vault
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.dbcertsecretprefix }} | jq -r 'if .errors then . else . end')         
-          validateVaultResponse "{{ .Values.vault.dbcertsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-          CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["mongoCA.crt"]')
+          echo "check-2"
+          validateVaultResponse "secret {{ .Values.vault.dbcertsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}"
+          echo "check-3"
+          CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["mongoCA.crt"]')
           echo "${CA_CERT}" | base64 -d > ${OUTPUT_PATH}/mongoCA.crt   
           echo "$CA_CERT"
           # add permissions to dir
@@ -242,44 +209,29 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-              validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
-                fi
-              }
+             validateVaultResponse () {
+             if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+              fi
+             }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
              # Login to Vault and so I can get an approle token
              VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
              validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
-             
+             echo "logged into vault"
              OUTPUT_PATH=${MOUNT_PATH}
              
              LOOKUP_PWD_RESPONSE_DB_PASS=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${DB_CRED_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-             validateVaultResponse "${DB_CRED_SECRET_PREFIX}" "${LOOKUP_PWD_RESPONSE_DB_PASS}" "LOOKUPSECRETRESPONSE"
-             MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE_DB_PASS} | jq -r '.data.data["mongodbPassword"]')
+             MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE_DB_PASS} | jq -r '.data["mongodbPassword"]')
           
              echo "${MONGODB_PASSWORD}" >> ${MOUNT_PATH}/db_root_password
              
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${USER_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-             validateVaultResponse "${USER_SECRET_PREFIX}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-             USER_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["{{ .Values.image.authusername }}"]')
+             validateVaultResponse "secret (${CERTS_SECRET_PREFIX})" "${LOOKUP_SECRET_RESPONSE}"
+             USER_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["{{ .Values.image.authusername }}"]')
              echo "${USER_PASSWORD}" >> ${MOUNT_PATH}/user_cred
              
         volumeMounts:
@@ -356,10 +308,11 @@ spec:
             claimName: {{ .Values.nodeName }}-pvc
         - name: certs
           emptyDir:
-            medium: Memory
+          medium: Memory
         - name: creds
           emptyDir:
-            medium: Memory
+          medium: Memory
         - name: tls-certs
           emptyDir:
-            medium: Memory
+          medium: Memory
+          
diff --git a/platforms/r3-corda/charts/nms/templates/deployment.yaml b/platforms/r3-corda/charts/nms/templates/deployment.yaml
--- a/platforms/r3-corda/charts/nms/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/nms/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 # Deployment
 # Creates the replicated container and manages lifecycle
 # TLS certs mounted
@@ -44,7 +38,6 @@ spec:
       containers:
       - name: {{ .Values.nodeName }}-service
         image: {{ .Values.image.containerName }}
-        imagePullPolicy: Always
         command: ["sh", "-c"]
         args:
         - |-
@@ -60,10 +53,7 @@ spec:
           - containerPort: {{ .Values.service.targetPort }}
         volumeMounts:
           - name: {{ .Values.nodeName }}-servicedata
-            mountPath: "{{ .Values.image.mountPath.basePath }}/db"
-            readOnly: false
-          - name: {{ .Values.nodeName }}-logs
-            mountPath: "{{ .Values.image.mountPath.basePath }}/logs"
+            mountPath: "{{ .Values.image.mountPath.basePath }}/db/"
             readOnly: false
           - name: certs
             mountPath: "{{ .Values.image.mountPath.basePath }}/db/certs"
@@ -71,36 +61,6 @@ spec:
           - name: creds
             mountPath: "/opt/creds"
             readOnly: false
-      - name: logs
-        image: "{{ .Values.image.initContainerName }}"
-        imagePullPolicy: {{ .Values.image.pullPolicy }}
-        command: ["sh", "-c"]
-        args:
-        - |-
-          cd /opt/networkmap/
-          COUNTER=1
-          NETWORK_ROOT_TRUST=/opt/networkmap/network-map-truststore.jks
-          while [ "$COUNTER" -le {{ $.Values.healthcheck.readinessthreshold }} ]
-          do
-            curl http://localhost:8080/network-map/truststore --output network-map-truststore.jks
-            if [ -f "$NETWORK_ROOT_TRUST" ]
-            then
-              echo "SUCCESS!"
-              echo "NMS running and fetched truststore"
-              break
-            else
-              COUNTER=`expr "$COUNTER" + 1`
-              sleep {{ $.Values.healthcheck.readinesscheckinterval }}
-            fi   
-          done 
-          if ["$COUNTER" -gt {{ $.Values.healthcheck.readinessthreshold }} ] 
-          then 
-            exit 1 
-          fi
-          while true; do tail -f ./logs/*.log 2>/dev/null; sleep 5; done
-        volumeMounts:
-        - name: {{ .Values.nodeName }}-logs
-          mountPath: "{{ .Values.image.mountPath.basePath }}/logs"
       initContainers:
       - name: init-certificates
         image: {{ .Values.image.initContainerName }}
@@ -122,26 +82,12 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-              validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
-                fi
-              }
+             validateVaultResponse () {
+             if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+              fi
+             }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
@@ -152,13 +98,13 @@ spec:
 
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.certsecretprefix }} | jq -r 'if .errors then . else . end')
 
-             validateVaultResponse "${{ .Values.vault.certsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+             validateVaultResponse "secret (${{ .Values.vault.certsecretprefix }})" "${LOOKUP_SECRET_RESPONSE}"
 
-             ROOTCA_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["rootcakey"]')
+             ROOTCA_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["rootcakey"]')
              mkdir -p ${OUTPUT_PATH}/root;
              echo "${ROOTCA_KEY}" | base64 -d > ${OUTPUT_PATH}/root/keys.jks
              
-             NETWORKMAP_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["networkmap.jks"]')
+             NETWORKMAP_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["networkmap.jks"]')
              mkdir -p ${OUTPUT_PATH}/network-map;
              echo "${NETWORKMAP_KEY}" | base64 -d > ${OUTPUT_PATH}/network-map/keys.jks
              
@@ -189,26 +135,12 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-              validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
-                fi
-              }
+             validateVaultResponse () {
+             if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+              fi
+             }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
@@ -219,14 +151,13 @@ spec:
              OUTPUT_PATH=${MOUNT_PATH}
              
              LOOKUP_PWD_RESPONSE_DB_PASS=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${DB_CRED_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-             validateVaultResponse "${DB_CRED_SECRET_PREFIX}" "${LOOKUP_PWD_RESPONSE_DB_PASS}" "LOOKUPSECRETRESPONSE"
-             MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE_DB_PASS} | jq -r '.data.data["mongodbPassword"]')
+             MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE_DB_PASS} | jq -r '.data["mongodbPassword"]')
           
              echo "${MONGODB_PASSWORD}" >> ${MOUNT_PATH}/db_root_password
              
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${USER_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
              validateVaultResponse "secret (${CERTS_SECRET_PREFIX})" "${LOOKUP_SECRET_RESPONSE}"
-             USER_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["{{ .Values.image.authusername }}"]')
+             USER_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["{{ .Values.image.authusername }}"]')
              echo "${USER_PASSWORD}" >> ${MOUNT_PATH}/user_cred
              
         volumeMounts:
@@ -301,12 +232,9 @@ spec:
         - name: {{ .Values.nodeName }}-servicedata
           persistentVolumeClaim:
             claimName: {{ .Values.nodeName }}-pvc
-        - name: {{ .Values.nodeName }}-logs
-          persistentVolumeClaim:
-            claimName: {{ .Values.nodeName }}-pvc-logs
         - name: certs
           emptyDir:
-            medium: Memory
+          medium: Memory
         - name: creds
           emptyDir:
-            medium: Memory
+          medium: Memory
diff --git a/platforms/r3-corda/charts/notary/templates/deployment.yaml b/platforms/r3-corda/charts/notary/templates/deployment.yaml
--- a/platforms/r3-corda/charts/notary/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/notary/templates/deployment.yaml
@@ -1,9 +1,3 @@
-##############################################################################################
-#  Copyright Accenture. All Rights Reserved.
-#
-#  SPDX-License-Identifier: Apache-2.0
-##############################################################################################
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -62,9 +56,7 @@ spec:
             
             # to clean network-parameters on every restart
             rm -rf ${BASE_DIR}/network-parameters
-
-            # Run schema migration scripts for corDApps
-            java -Djavax.net.ssl.keyStore=${BASE_DIR}/certificates/sslkeystore.jks -Djavax.net.ssl.keyStorePassword=newpass $JAVA_OPTIONS -jar ${CORDA_HOME}/corda.jar run-migration-scripts --core-schemas --app-schemas --base-directory=${BASE_DIR}
+            
             # command to run corda jar, we are setting javax.net.ssl.keyStore as ${BASE_DIR}/certificates/sslkeystore.jks since keystore gets reset when using h2 ssl 
             java -Djavax.net.ssl.keyStore=${BASE_DIR}/certificates/sslkeystore.jks -Djavax.net.ssl.keyStorePassword=newpass $JAVA_OPTIONS -jar ${CORDA_HOME}/corda.jar --base-directory=${BASE_DIR}
           resources:
@@ -124,7 +116,7 @@ spec:
             
             # save networkmap login passwoed from vault
             LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${SECRET_PREFIX} | jq -r 'if .errors then . else . end')                            
-            NMS_USER_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["sa"]')                          
+            NMS_USER_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["sa"]')                          
                        
             STATUS=0
             
@@ -168,7 +160,7 @@ spec:
                     if [ $response = "OK" ]
                     then
                         echo "Response is OK";
-                        echo "Registered notary with Networkmap successfully"
+                        echo "Registered notary with Networkmap sucessfully"
                     else
                         echo "Response from NMS is not ok";
                         echo "Something went wrong"
@@ -177,15 +169,21 @@ spec:
                     STATUS=1
                     break
                 fi
-            done               
-            if [ -e ${BASE_DIR}/logs/node-{{ .Values.nodeName }}.log ]
-            then
-              clear
-              tail -f ${BASE_DIR}/logs/node-{{ .Values.nodeName }}.log
-            else
-              echo "waiting for corda to generate log, sleeping for 10s"
-              sleep {{ $.Values.healthcheck.readinesscheckinterval }}
-            fi
+            done  
+
+            # while loop to check if log file is generated by corda and keep on printing log file if it is generated by corda
+            while [ "$COUNTER" -ne 1 ]
+            do
+                 
+                if [ -e ${BASE_DIR}/logs/node-{{ .Values.nodeName }}.log ]
+                then
+                  clear
+                  tail -n 30 ${BASE_DIR}/logs/node-{{ .Values.nodeName }}.log
+                else
+                  echo "waiting for corda to generate log, sleeping for 10s"
+                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+                fi
+            done
           volumeMounts:
           - name: notary-volume
             mountPath: "{{ $.Values.volume.baseDir }}"
@@ -207,26 +205,12 @@ spec:
           args:
           - |-
               #!/usr/bin/env sh
-              validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                      echo "Http response code from Vault - $http_code"
-                      if test "$curl_response" != "0"; then
-                        echo "Error: curl command failed with error code - $curl_response"
-                        exit 1
-                      fi
-                  fi
-                fi
-              }
+               validateVaultResponse () {
+                 if echo ${2} | grep "errors"; then
+                    echo "ERROR: unable to retrieve ${1}: ${2}"
+                    exit 1
+                 fi
+               }
 
               # setting up env to get secrets from vault
               echo "Getting secrets from Vault Server"
@@ -290,12 +274,12 @@ spec:
 
             # save keyStorePassword & trustStorePassword from vault
             LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${KS_SECRET_PREFIX} | jq -r 'if .errors then . else . end')          
-            CONF_KEYSTOREPASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["keyStorePassword"]')
-            CONF_TRUSTSTOREPASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["trustStorePassword"]')
+            CONF_KEYSTOREPASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["keyStorePassword"]')
+            CONF_TRUSTSTOREPASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["trustStorePassword"]')
 
             # save dataSourceUserPassword from vault
             LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${DB_SECRET_PREFIX} | jq -r 'if .errors then . else . end')           
-            CONF_DATASOURCEPASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["{{ .Values.credentials.dataSourceUser }}"]')
+            CONF_DATASOURCEPASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["{{ .Values.credentials.dataSourceUser }}"]')
             LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${RPCUSER_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
 
             #For more information for node.Conf fields please refer to: https://docs.corda.r3.com/releases/4.0/corda-configuration-file.html
@@ -308,7 +292,6 @@ spec:
             attachmentContentCacheSizeMegaBytes : {{ .Values.nodeConf.attachmentContentCacheSizeMegaBytes }}
             attachmentCacheBound : {{ .Values.nodeConf.attachmentCacheBound }}
             notary : {
-                serviceLegalName : "{{ .Values.nodeConf.notary.serviceLegalName }}"
                 validating : {{ .Values.nodeConf.notary.validating }}
             }
             detectPublicIp = {{ .Values.nodeConf.detectPublicIp }}
@@ -321,6 +304,7 @@ spec:
                 dataSource.password = "${CONF_DATASOURCEPASSWORD}"
             }
             database = {
+                transactionIsolationLevel = {{ .Values.nodeConf.database.transactionIsolationLevel }}
                 exportHibernateJMXStatistics = {{ .Values.nodeConf.database.exportHibernateJMXStatistics }}
             }
             jarDirs = [{{ .Values.nodeConf.jarPath }}]
@@ -377,7 +361,7 @@ spec:
                echo 'rpcUsers : [' >> ${BASE_DIR}/node.conf
                {{- range $.Values.credentials.rpcUser }}
                echo '{ username={{ .name }} ,permissions={{ .permissions }}, ' >> ${BASE_DIR}/node.conf
-               echo " password=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["{{ .name }}"]') }" >> ${BASE_DIR}/node.conf
+               echo " password=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["{{ .name }}"]') }" >> ${BASE_DIR}/node.conf
                {{- end }}
                echo ']' >> ${BASE_DIR}/node.conf
             fi
@@ -391,8 +375,8 @@ spec:
                adminAddress = "{{ .Values.nodeConf.rpcSettings.adminAddress }}"
                useSsl = {{ .Values.nodeConf.rpcSettings.useSsl }}
                ssl = {
-                  keyStorePassword = $(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["sslkeyStorePassword"]')
-                  trustStorePassword = $(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["ssltrustStorePassword"]')
+                  keyStorePassword = $(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["sslkeyStorePassword"]')
+                  trustStorePassword = $(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["ssltrustStorePassword"]')
                   certificatesDirectory = ${BASE_DIR}/{{ .Values.nodeConf.rpcSettings.ssl.certificatesDirectory }}
                   sslKeystore = ${BASE_DIR}/{{ .Values.nodeConf.rpcSettings.ssl.certificatesDirectory }}/{{ .Values.nodeConf.rpcSettings.ssl.sslKeystoreFileName }}
                   trustStoreFile = ${BASE_DIR}/{{ .Values.nodeConf.rpcSettings.ssl.certificatesDirectory }}/{{ .Values.nodeConf.rpcSettings.ssl.trustStoreFileName }}
@@ -433,26 +417,12 @@ spec:
           args:
           - |-
                #!/usr/bin/env sh
-                validateVaultResponse () {
-                  if echo ${2} | grep "errors"; then
-                    echo "ERROR: unable to retrieve ${1}: ${2}"
-                    exit 1
-                  fi
-                  if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                  then
-                    http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                    --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                    ${VAULT_ADDR}/v1/${1})
-                    curl_response=$?
-                    if test "$http_code" != "200" ; then
-                        echo "Http response code from Vault - $http_code"
-                        if test "$curl_response" != "0"; then
-                          echo "Error: curl command failed with error code - $curl_response"
-                          exit 1
-                        fi
-                    fi
-                  fi
-                }
+               validateVaultResponse () {
+               if echo ${2} | grep "errors"; then
+                echo "ERROR: unable to retrieve ${1}: ${2}"
+                exit 1
+                fi
+               }
                # setting up env to get secrets from vault
                echo "Getting secrets from Vault Server"
                KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
@@ -463,26 +433,26 @@ spec:
                
                # get nodekeystore.jks from vault
                LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/nodekeystore | jq -r 'if .errors then . else . end')
-               validateVaultResponse "${CERTS_SECRET_PREFIX}/nodekeystore" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-               TLS_NODEKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["nodekeystore.jks"]')
+               validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/nodekeystore)" "${LOOKUP_SECRET_RESPONSE}"
+               TLS_NODEKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["nodekeystore.jks"]')
                echo "${TLS_NODEKEYSTORE}" | base64 -d > ${OUTPUT_PATH}/nodekeystore.jks
 
                # get sslkeystore.jks from vault
                LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/sslkeystore | jq -r 'if .errors then . else . end')
-               validateVaultResponse "${CERTS_SECRET_PREFIX}/sslkeystore" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-               TLS_SSLKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["sslkeystore.jks"]')
+               validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/sslkeystore)" "${LOOKUP_SECRET_RESPONSE}"
+               TLS_SSLKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["sslkeystore.jks"]')
                echo "${TLS_SSLKEYSTORE}" | base64 -d > ${OUTPUT_PATH}/sslkeystore.jks
 
                # get truststore.jks from vault
                LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/truststore | jq -r 'if .errors then . else . end')
-               validateVaultResponse "${CERTS_SECRET_PREFIX}/truststore" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-               TLS_TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["truststore.jks"]')
+               validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/truststore)" "${LOOKUP_SECRET_RESPONSE}"
+               TLS_TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["truststore.jks"]')
                echo "${TLS_TRUSTSTORE}" | base64 -d > ${OUTPUT_PATH}/truststore.jks
                 
                # get network-map-truststore.jks from vault
                LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/networkmaptruststore | jq -r 'if .errors then . else . end')
-               validateVaultResponse "${CERTS_SECRET_PREFIX}/networkmaptruststore" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-               TLS_NMS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["network-map-truststore"]')
+               validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/networkmaptruststore)" "${LOOKUP_SECRET_RESPONSE}"
+               TLS_NMS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["network-map-truststore"]')
                echo "${TLS_NMS}" | base64 -d > ${OUTPUT_PATH}/network-map-truststore.jks
 
                # when using doorman and networkmap in TLS: true, and using private certificate then download certificate
@@ -492,13 +462,13 @@ spec:
                    mkdir -p ${OUTPUT_PATH}/doorman
 
                    LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/networkmap | jq -r 'if .errors then . else . end')
-                   validateVaultResponse "${CERTS_SECRET_PREFIX}/networkmap" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-                   NETWORKMAP_CRT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["networkmap.crt"]')
+                   validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/networkmap)" "${LOOKUP_SECRET_RESPONSE}"
+                   NETWORKMAP_CRT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["networkmap.crt"]')
                    echo "${NETWORKMAP_CRT}" | base64 -d > ${OUTPUT_PATH}/networkmap/networkmap.crt
 
                    LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/doorman | jq -r 'if .errors then . else . end')
-                   validateVaultResponse "${CERTS_SECRET_PREFIX}/doorman" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-                   DOORMAN_CRT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["doorman.crt"]')
+                   validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/doorman)" "${LOOKUP_SECRET_RESPONSE}"
+                   DOORMAN_CRT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["doorman.crt"]')
                    echo "${DOORMAN_CRT}" | base64 -d > ${OUTPUT_PATH}/doorman/doorman.crt
                fi
                
@@ -510,13 +480,13 @@ spec:
                   SSL_CERT_PATH={{ .Values.nodeConf.rpcSettings.ssl.certificatesDirectory }}
                   SSL_KEYSTORE_FILE_NAME_KEY={{ .Values.nodeConf.rpcSettings.ssl.sslKeystoreFileName }}
                   LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/${SSL_KEYSTORE_FILE_NAME_KEY} | jq -r 'if .errors then . else . end')
-                  validateVaultResponse "${CERTS_SECRET_PREFIX}/${SSL_KEYSTORE_FILE_NAME_KEY}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-                  SSLKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["SSL_KEYSTORE_FILE_NAME_KEY"]')
+                  validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/${SSL_KEYSTORE_FILE_NAME_KEY})" "${LOOKUP_SECRET_RESPONSE}"
+                  SSLKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["SSL_KEYSTORE_FILE_NAME_KEY"]')
                   echo "${SSLKEYSTORE}" | base64 -d > ${OUTPUT_PATH}/${SSL_CERT_PATH}/${SSL_KEYSTORE_FILE_NAME_KEY}
                   TRUSTKEYSTORE_FILE_NAME_KEY={{ .Values.nodeConf.rpcSettings.ssl.sslKeystoreFileName }}
                   LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/${TRUSTKEYSTORE_FILE_NAME_KEY} | jq -r 'if .errors then . else . end')
-                  validateVaultResponse "${CERTS_SECRET_PREFIX}/${TRUSTKEYSTORE_FILE_NAME_KEY}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-                  TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["TRUSTKEYSTORE_FILE_NAME_KEY"]')
+                  validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/${TRUSTKEYSTORE_FILE_NAME_KEY})" "${LOOKUP_SECRET_RESPONSE}"
+                  TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["TRUSTKEYSTORE_FILE_NAME_KEY"]')
                   echo "${TRUSTSTORE}" | base64 -d > ${OUTPUT_PATH}/${SSL_CERT_PATH}/${TRUSTKEYSTORE_FILE_NAME_KEY}
                else
                   echo ""
@@ -582,22 +552,22 @@ spec:
           args:
           - |-
             # crearting cordapps dir in volume to keep jars
-            mkdir -p {{ .Values.volume.baseDir }}/cordapps
             {{- if .Values.cordapps.getcordapps }}
+              mkdir -p {{ .Values.volume.baseDir }}/cordapps
               mkdir -p /tmp/downloaded-jars
               # setting up env to get secrets from vault
               KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
               echo "Getting secrets from Vault Server"
               VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
               
-              # save cordapps repository login password from vault
+              # save networkmap login password from vault
               LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${SECRET_PREFIX} | jq -r 'if .errors then . else . end')                            
-              REPO_USER_PASS=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["repo_password"]')
-              REPO_USER=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data.data["repo_username"]')
+              REPO_USER_PASS=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["repo_password"]')
+              REPO_USER=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["repo_username"]')
               
               # Downloading official corda provided jars using curl 
               {{- range .Values.cordapps.jars }}
-                cd /tmp/downloaded-jars && curl -u  $REPO_USER:$REPO_USER_PASS -O -L {{ .url }}
+                cd /tmp/downloaded-jars && curl -u  $REPO_USER:$REPO_USER_PASS -O -J {{ .url }}
               {{- end }}
               cp -ar /tmp/downloaded-jars/* {{ $.Values.volume.baseDir }}/cordapps
             {{- end }}  
